assets/dex/dedust.json, assets/dex/stormtrade.json, assets/gaming/bums.json, assets/lending/coffin.json, assets/lending/evaa.json, assets/lending/factorial.json, assets/scammer/scammer.json, tags.json
After merging, we need to update dune.com/ton_foundation/evaa dashboard to use only EVAA addresses with "pool" tag. Otherwise the reward payouts will be treated as a withdraws from the protocol which will add errors in the TVL calculation assumptions we have.
=> Add EVAA, Factorial and a "pool" tag

assets/dex/ston.fi.json
HEX: `0:091b9a7264f58489088c54975fedb0d18112f383a411e7ba8a791b0eacc3be9d`
Bounceable: `EQAJG5pyZPWEiQiMVJdf7bDRgRLzg6QR57qKeRsOrMO-ncZN`
Non-bounceable: `UQAJG5pyZPWEiQiMVJdf7bDRgRLzg6QR57qKeRsOrMO-nZuI`
When swapping certain tokens through stonfi UI, their backend returns this address as router
----
My address for rewards: `UQDeai4M51qCJnvxfJPl4U2S8MGJ9fx_0xb4fXjk8GewV-YD`
=> Add stonfi router label

assets/gaming/splash.json
HEX: 0:840346f15339259a6c612adf9ceea670efe2b637e5f0f1f0ac51567ccede3309
Bounceable: EQCEA0bxUzklmmxhKt-c7qZw7-K2N-Xw8fCsUVZ8zt4zCbEg
Non-bounceable: UQCEA0bxUzklmmxhKt-c7qZw7-K2N-Xw8fCsUVZ8zt4zCezl
It's an address for tbook x splash airdrop campaign, here're screenshots from tbook chat (apparently they have some claiming issues atm)
=> Add label for another splash airdrop address

assets/cex/metka.json
HEX:
0:34128BADF3E08155491B22144B0C39678547B17DA449AC20BE34B5E0EAE916FF
Bounceable:
EQA0Eout8-CBVUkbIhRLDDlnhUexfaRJrCC-NLXg6ukW_2Y7
UQA0Eout8-CBVUkbIhRLDDlnhUexfaRJrCC-NLXg6ukW_zv-
This address belongs to the Metka exchange
It is also listed on BestChange, with a link leading to the website metka.cc
I exchanged TON for USDT on TON. Initially, the funds were sent to a new intermediate deposit wallet -
UQDAn9flPU0nG08xb7bamDSUVb_0IFqIBxRKpEFNv344DfGI
Bounceable:
EQDAn9flPU0nG08xb7bamDSUVb_0IFqIBxRKpEFNv344DaxN
https://tonviewer.com/transaction/a61118ecddf35d66ed4c2aee3979769dcfb29e897b860a913edfa2b8f6dd6f47
After 20 minutes, the funds were sent to Metka main wallet 
https://tonviewer.com/transaction/f7a791372c9d0e4776ed1bd2bae9636198382efc40ecd407ef368953a4fa …
=> Create metka.json & label

assets/wallet/pocketfi.json
HEX:
0:C8D273C0327B1CF3CC3BF1D8F3F72E4DC294DADB14F98EE5708B0DF24AC04742
Bounceable:
EQDI0nPAMnsc88w78djz9y5NwpTa2xT5juVwiw3ySsBHQnca
UQDI0nPAMnsc88w78djz9y5NwpTa2xT5juVwiw3ySsBHQirf
The wallet belongs to PocketFI and is used for $SWITCH autoclaim payments
https://tonviewer.com/transaction/98b6aab8cac03c4c21e7783b362460f3558604b49da6e08fe7d82c9e1bb6e0f9
=> Add pocketfi label

assets/cex/kucoin.json
I think, this is a Kucoin address! No direct evidence, so let's discuss. 
My proofs:
Deployed from https://tonviewer.com/0:847ed4f21a71bc2d115085cecf04ed8e714772e6fabec2b8b5ac65c7630d50c8 (unknown address yet). 
2nd transaction is also from unknown highload wallet (probably CEX) https://tonviewer.com/UQDNH6P8W4f68LRScjwuqhee5SgP9btMzoESFu8ewzRuDQ1o
Source: 
https://dune.com/okhlopkov/ton-wallet-analysis?wallet_address_td90d4=0:4fc9e9911100254b104975602b949097b63cdc38f0672a2c16cfcb30f7ff0bff
=> Add kucoin address

assets/cex/coinex.json
HEX: ``0:14de4b02647941779108b7b99be85596260ccde813351000055d744dd8aba04c``
Bounceable: ``EQAU3ksCZHlBd5EIt7mb6FWWJgzN6BM1EAAFXXRN2KugTMvg``
Non-bounceable: ``UQAU3ksCZHlBd5EIt7mb6FWWJgzN6BM1EAAFXXRN2KugTJYl``
You can check that address in fact belongs to CoinEx by going to thei proof-of-reserves [page](https://www.coinex.com/en/reserve-proof) and downloading xlsx table there, here is the row from it
My address for rewards: ``UQCBirB-586qkioRmyqPgn9y3_GVaXMl_mA9MBxt2BK__Iyp``
=> Add CoinEx label

assets/gaming/treeton.json
HEX: 0:2cf85023f96dd9660ffc8b8c839c3d3c1ffc1b6962ba95ba18b2ab51669001c0
Bounceable: EQAs-FAj-W3ZZg_8i4yDnD08H_wbaWK6lboYsqtRZpABwLGh
Non-bounceable: UQAs-FAj-W3ZZg_8i4yDnD08H_wbaWK6lboYsqtRZpABwOxk
Address is sending $TREES tokens and is hardcoded in telegram miniapp
---
=> Add treeton address

assets/gaming/tonbitcoin.json
HEX: 0:46e4bffcca0280c57d80bf283a9fbbaf3fdddb71bfb293421add8bae1fd5db66
Bounceable: EQBG5L_8ygKAxX2Avyg6n7uvP93bcb-yk0Ia3YuuH9XbZhrS
Non-bounceable: UQBG5L_8ygKAxX2Avyg6n7uvP93bcb-yk0Ia3YuuH9XbZkcX
Address is sending kw tokens to users wallets (it's one of the tokens in tbtc ecosystem)
In official miniapp chat, one of co-founders said that it's address for token distribution
---
=> Add tonbitcoin

assets/wallet/mytonwallet.json
HEX: 0:d49106e94d5220b7bbfaebe253151fb7f9e5d1173ff857ae85f947e7eaf3a0d0
Bounceable: EQDUkQbpTVIgt7v66-JTFR-3-eXRFz_4V66F-Ufn6vOg0D5s
Non-bounceable: UQDUkQbpTVIgt7v66-JTFR-3-eXRFz_4V66F-Ufn6vOg0GOp
The address is hardcoded in the mytonwallet config in their github repo
And, looking at transactions, it collects some % of tokens after users' swap
---
=> Add mytonwallet fee collector

assets/cex/bybit.json
HEX:
0:CF7EA235ED6F6517EDCE98026EF7618E9F6D81A1331D4E65BA718E2CD15F80AD
Bounceable:
EQDPfqI17W9lF-3OmAJu92GOn22BoTMdTmW6cY4s0V-ArRRY
UQDPfqI17W9lF-3OmAJu92GOn22BoTMdTmW6cY4s0V-ArUmd
I checked all the labeled Bybit wallets that were involved in Notcoin deposits and withdrawals. All of them transferred their Notcoin to a new address between September 15 and 18, after which they were no longer used
Here are the wallets (they are all labeled):
EQATjYSGQhI_OhXB0ch4HAEKu2cSu0CwV0fhb-70lCOXgeaZ
EQCge0fy6N9JAnWDassuKu3WL5B4GADfzvmiT9wLok4YdPrI
EQCuf9xA0lPsnfpy2ux7qcKBk82Hg39vAUV0OS0AJQeNllht
EQCtcRV4-JH-3AatB9l0_EXgBqH34QW2gveNoXr2ilMUr31Q
EQCqDMN6cKPqetfkJlw6bcsXJrCB4-aKSSUaqJ0m37__DJgC
EQD1AmltGL9X8y9Y0OZVITEHOZ5mCalvcqhEPUSM2gjes_Hk …
=> Add bybit label

assets/wallet/tonapi.json
A bunch of contracts like this:
https://tonviewer.com/UQBRs2Mf4_kVmB9BFM3rEjfoULf65DBVsT283JblDxwWzlWt
TON API Docs on Gasless: 
https://docs.tonconsole.com/tonapi/rest-api/gasless
I'm not sure what should be the best category and label for these contracts but since these gasless things are added to a bunch of wallets, I chose 'wallet' category.
=> Add TON API Gas proxy contracts

assets/gaming/kitty_verse.json
**Hex**: 0:412451AE5C7AE4A427DA58D02BFE6D3A3DB4602C4C2A87021B60ACA974189577
**Bounceable**: EQBBJFGuXHrkpCfaWNAr_m06PbRgLEwqhwIbYKypdBiVdyeH
**Non-bounceable**: UQBBJFGuXHrkpCfaWNAr_m06PbRgLEwqhwIbYKypdBiVd3pC
This address has a lot of outgoing transactions with "KittyVerse: Refund" comments:
In Project whitepaper (it's not currently available on site, idk why) we can find [this](https://tonviewer.com/EQDr6eSxPx3olIc5NfPfBTXvK2rU0HIAobR1reGjZLRTVneX) address as address for presale:
In [tonviewer](https://tonviewer.com/transaction/a26d97242c0fc0a2dff7aa34cf8a407a54fe754e4d304ce560e2f8dec654ed8d) we can find a lot of transactions, where presale address sends a lot of ton to refund address ([1](https://tonviewer.com/transaction/4316a854a87949fb17203ea979f153f02b08bf48c68ea87d84f89d7a34971ee9) …
=> Address for KittyVerse

assets/gaming/wuffi.json
HEX: 0:f45022e3b56bb97eb621949be1ea98bc01d2ade981d4e29826f32d34ce2abc78
Bounceable: EQD0UCLjtWu5frYhlJvh6pi8AdKt6YHU4pgm8y00ziq8eGB7
Non-bounceable: UQD0UCLjtWu5frYhlJvh6pi8AdKt6YHU4pgm8y00ziq8eD2-
Address is hardcoded in telegram miniapp
And is used to claim WUF tokens
---
=> Add wuffi rewards address

assets/cex/wallex.json
HEX:
0:c7b93d8a8aee6cbee38043d25dbb48ca690d13070c310dffb7a2ec4797cf9179
Bounceable:
EQDHuT2Kiu5svuOAQ9Jdu0jKaQ0TBwwxDf-3ouxHl8-RebaI
UQDHuT2Kiu5svuOAQ9Jdu0jKaQ0TBwwxDf-3ouxHl8-ReetN
my wallet address:
This PR adds https://wallex.ir to the list of exchanges.
wallex is a cryptocurrency exchange based in Iran.
=> add wallex exchange

assets/merchant/split.tg.json
HEX:
0:8c069c61735e6c7565539ec8c4638ece8f93a3e19b9082ae3358ed343997f1d7
Bounceable:
EQCMBpxhc15sdWVTnsjEY47Oj5Oj4ZuQgq4zWO00OZfx1_v4
UQCMBpxhc15sdWVTnsjEY47Oj5Oj4ZuQgq4zWO00OZfx16Y9
HEX:
0:0ae76c4a88a5cdf1111742d3ed067bb16a0b2f96d45537dc4ee196ded34da465
Bounceable:
EQAK52xKiKXN8REXQtPtBnuxagsvltRVN9xO4Zbe002kZXVD
UQAK52xKiKXN8REXQtPtBnuxagsvltRVN9xO4Zbe002kZSiG
HEX:
0:f885156931dbd1bd5aad82a07c26d9ef61e5d4941bec0b1cefa69379a71c5f25
Bounceable:
EQD4hRVpMdvRvVqtgqB8JtnvYeXUlBvsCxzvppN5pxxfJXds
UQD4hRVpMdvRvVqtgqB8JtnvYeXUlBvsCxzvppN5pxxfJSqp
HEX:
0:1c2201823e6dae55fadd08cad27845c77267c462d81b0620fe664dee28bb8e34
Bounceable:
EQAcIgGCPm2uVfrdCMrSeEXHcmfEYtgbBiD-Zk3uKLuONI9n
UQAcIgGCPm2uVfrdCMrSeEXHcmfEYtgbBiD-Zk3uKLuONNKi
These …
=> Add split.tg labels

assets/cex/bingx.json, assets/cex/bitget.json, assets/cex/bitmart.json, assets/cex/bittime.json, assets/cex/bybit.json, assets/cex/crypto.com.json, assets/cex/crypto_bot.json, assets/cex/excoino.json, assets/cex/hitbtc.json, assets/cex/huobi.json, assets/cex/kraken.json, assets/cex/lbank.info.json, assets/cex/metka.json, assets/cex/okx.json, assets/cex/tabdeal.json, assets/cex/toobit.json, assets/cex/wallet_in_telegram.json, assets/cex/wallex.json, assets/cex/whitebit.json, assets/cex/xrocket.json, assets/gaming/1xbet.json, assets/gaming/dinodrop.json, assets/gaming/rebor.json, assets/gaming/ton_miner.json, assets/gaming/tonpoker.json, assets/gaming/voxel.json, assets/gaming/whalecasino.json, assets/merchant/cryptomus.json, tags.json
These orgs doesn't have deposits via custodial wallets for now:
```
'pocketfi', 'miomi_game', 'wcoin', 
'paws', 'goblin_mine', 'boinkers',
'pluto_studio',
'binance', 'fixedfloat', 'mexc', 'fragment', 'gameness', 'pixiland', 
'huobi', 'gate.io', 'tonnel', 'bridgers', 'redcoin', '0xiceberg',
'omni_points', 'bountybay', 'memhash', 'tonstakers', 'nobitex', 'split.tg', 'dropee',
'vertus', 'blum', 'seed_analytics', 'goats', 'tomarket', 'not_pixel', 'tonstation',
'memefi', 'okx', 'sidekick_labs', 'bbq_coin', 'yescoin', 'piggypiggy', 'tonkeeper', 'dedust', 'bums', 'rebor',
'cwallet', 'bitpin', 'coinex', 'kucoin', 'ton.fun', 'major', 'nexusverse', 'major',
'starhash', 'merge_pals', 'money_dogs', 'marketapp', 'wonton'
```
These ones have:
```
'wallet_in_telegram', 'tonpoker', 'metka', 'cryptomus', …
```
=> Add custodial wallet tag and label addresses

assets/gaming/ton_mine.json
These addresses were posted in official bot' news group (https://t.me/TonMineNews/40). 
They're used for distributing rewards
---
HEX: 0:60e0cef9661d5ac6d70dd14eff18b8f9988673f2109b48e2b7a3fa9c410214e0
Bounceable: EQBg4M75Zh1axtcN0U7_GLj5mIZz8hCbSOK3o_qcQQIU4Fkm
Non-bounceable: UQBg4M75Zh1axtcN0U7_GLj5mIZz8hCbSOK3o_qcQQIU4ATj
---
HEX: 0:ead0e52c0f480ae35b02e03591b1aca7cdeaae25ee3d63bd2c8952ccd30de97a
Bounceable: EQDq0OUsD0gK41sC4DWRsaynzequJe49Y70siVLM0w3peop5
Non-bounceable: UQDq0OUsD0gK41sC4DWRsaynzequJe49Y70siVLM0w3pete8
---
**_This one is not participating in labeling contest_**
HEX:
0:ecf9a17fbaaafca8123290dbee6ee4c8f36ad8039c7836d8379b0e9bcf1817a8
Bounceable: EQDs-aF_uqr8qBIykNvubuTI82rYA5x4Ntg3mw6bzxgXqDL_
Non-bounceable: UQDs-aF_uqr8qBIykNvubuTI82rYA5x4Ntg3mw6bzxgXqG86
---
My …
=> Add tonmine labels

assets/scripted-activity/sybil_EQD4Hotb.json
- **HEX Address:**
```
0:f81e8b5b9443ff9f3fe1f01e4b4416458f50b548c7777e717a742e3c9abcdab9
```
- **Bounceable Address:**
```
EQD4HotblEP_nz_h8B5LRBZFj1C1SMd3fnF6dC48mrzauXbJ
```
- **Non-Bounceable Address:**
```
UQD4HotblEP_nz_h8B5LRBZFj1C1SMd3fnF6dC48mrzauSsM
```
This address is used to send **0.006 TON** to multiple addresses, presumably to trigger operations on the `@wcoin_tapbot`.
---
- **TON Address:**
```
UQBe9ai1rktFr8pDQlb-iBEkpVDiKAqrXALdu8GRr7GYuZCc
```
=> sybil_EQD4Hotb.json

assets/merchant/ecorpay.json
HEX: 0:90dd72026abaf6672b7c263bacd7c01d9089dfe99aa6af1c76e03b49a8575bb5
Bounceable: EQCQ3XICarr2Zyt8Jjus18AdkInf6Zqmrxx24DtJqFdbtaAr
Non-bounceable: UQCQ3XICarr2Zyt8Jjus18AdkInf6Zqmrxx24DtJqFdbtf3u
Address is distributing ECOR token to different addresses
It was funded from the token owner in two transactions ([1](https://tonviewer.com/transaction/cbd55204d1dde525ce002721755af996fff7fe69bf7c6be33a2821886396aa66), [2](https://tonviewer.com/transaction/fe7115830ee96879c6b5d93395838acbeed70078355e7403cf3f134bfa8d7efb)) or 12mil tokens
_owner and airdrop address in token top holders list_
I added it to merchant because ecorpay.com seems to be a legit payment provider, and the token landing page is hosted on their subdomain
---
My address for rewards: …
=> Add ecorpay airdrop address

assets/cex/okx.json
All the addresses from OKX Proof of Reserves were labelled.
Custodial wallets Materialised View: https://dune.com/queries/5032986?sidebar=none
Labelling helper function: https://dune.com/queries/5138647?sidebar=none
=> Add final OKX addresses

assets/merchant/mrkt.json
All these wallets are top-up helper wallets for mrkt. Addresses are randomly (?) generated each time user opens the app and are sent as config over http
HEX: 0:36bcbaba93714d7aa8ede7c518814712196179121e9f436819d70858254caffc
Bounceable: EQA2vLq6k3FNeqjt58UYgUcSGWF5Eh6fQ2gZ1whYJUyv_Cps
Non-bounceable: UQA2vLq6k3FNeqjt58UYgUcSGWF5Eh6fQ2gZ1whYJUyv_Hep
---
HEX: 0:4ffc9d6b1e44445357edbfa5d2d48f541cdada81614c6a9667ce067338282304
Bounceable: EQBP_J1rHkREU1ftv6XS1I9UHNragWFMapZnzgZzOCgjBIiO
Non-bounceable: UQBP_J1rHkREU1ftv6XS1I9UHNragWFMapZnzgZzOCgjBNVL
---
HEX: 0:4166a8aecff2664d0ea6a1ba1726f943ca440a1e6381cb15c5451e8f45a658dd
Bounceable: EQBBZqiuz_JmTQ6moboXJvlDykQKHmOByxXFRR6PRaZY3U36
Non-bounceable: UQBBZqiuz_JmTQ6moboXJvlDykQKHmOByxXFRR6PRaZY3RA_
---
My address for rewards: …
=> Add mrkt topup addresses

assets/gaming/puparty.json
HEX: 0:8e2c93b676f26c5c9d54372c73793c2e4c4bda257cebe229eaaf17a13c42a0db
Bounceable: EQCOLJO2dvJsXJ1UNyxzeTwuTEvaJXzr4inqrxehPEKg28Ay
Non-bounceable: UQCOLJO2dvJsXJ1UNyxzeTwuTEvaJXzr4inqrxehPEKg2533
The wallets triggering this smart contract are being topped up from the marked puparty address
And the admins in official chat are saying that withdrawals are made through this contract
[tx address in message](https://tonviewer.com/transaction/6684e1cd8b1874951ecfa4b10d2e9c48afe68695ff14a504200d28e296d580ef)
---
=> Add puparty withdrawals address

assets/other/verem.json
HEX: 0:94de6ebca2ecc8d1446e08da4970619bc481c2aea4601eb12cf517e1dc83f787
Bounceable: EQCU3m68ouzI0URuCNpJcGGbxIHCrqRgHrEs9Rfh3IP3h810
Non-bounceable: UQCU3m68ouzI0URuCNpJcGGbxIHCrqRgHrEs9Rfh3IP3h5Cx
The address gets VEREM tokens from the same source as the previously marked one and then distributes in small amounts to different wallets
---
My address UQDeai4M51qCJnvxfJPl4U2S8MGJ9fx_0xb4fXjk8GewV-YD
=> Add another verem distributor

assets/scripted-activity/sybil_EQApab.json
HEX: 0:2969bfedf3693ac49d6b6591c3408524c268b998e52dd3d107931d5a89d69fcc
Bounceable: EQApab_t82k6xJ1rZZHDQIUkwmi5mOUt09EHkx1aidafzIs-
Non-bounceable: UQApab_t82k6xJ1rZZHDQIUkwmi5mOUt09EHkx1aidafzNb7
Based on the transaction history, it looks like this address is part of a Sybil setup controlled by one person. The wallets receiving funds from the main address we’re trying to label show very similar patterns of behavior, which suggests they’re all managed by the same individual.
https://tonviewer.com/transaction/a4659f641b32581210e1bb3bd209a9cb208851b96b83823e1dd21a9ef0d5b839
Based on these transactions, we can see that the wallets showed identical activity and were used to win in the Sticker Store raffle.
https://tonviewer.com/transaction/2f8e38d837e265a556e01fa59e7c1d99dd643a047b2a797c460dc …
=> add sybil adress

assets/cex/nobitex.json
1) HEX: 0:dea2426f885320bd0a1c524fdbed0f9db77502ee4396b5a11aa839ce069789b7
Bounceable: EQDeokJviFMgvQocUk_b7Q-dt3UC7kOWtaEaqDnOBpeJt9dB
Non-bounceable: UQDeokJviFMgvQocUk_b7Q-dt3UC7kOWtaEaqDnOBpeJt4qE
2) HEX: 0:61b26c333345fdff5023ddd0965175983488e3d0900fa01ddeda25e256b3932a
Bounceable: EQBhsmwzM0X9_1Aj3dCWUXWYNIjj0JAPoB3e2iXiVrOTKvAq
Non-bounceable: UQBhsmwzM0X9_1Aj3dCWUXWYNIjj0JAPoB3e2iXiVrOTKq3v
My wallet for rewards: UQAjecHzmpKf8dkLDdI80RBZy39mEYoLn3LMx8RWe1lObcCu
Proofs:
I believe that these two addresses belong to the Nobitex exchange and are used for withdrawals, and here’s why I think so:
https://intel.arkm.com/explorer/address/0:61B26C333345FDFF5023DDD0965175983488E3D0900FA01DDEDA25E256B3932A
https://intel.arkm.com/explorer/address/0:dea2426f885320bd0a1c524fdbed0f9db77502ee4396b5 …
=> Add new Nobitex addresses

assets/gaming/xdao.json
HEX:
0:3b7c53843ab780c26fc101921e4d09ccc9a4cca675b80160ae9d37f148e52c9a
Bounceable: EQA7fFOEOreAwm_BAZIeTQnMyaTMpnW4AWCunTfxSOUsmlRi
This address belongs to xdao It is used in creating DAOs for users
Proofs:
The address was shown in the Xdao DAO creation guide:
https://lowly-eagle-a52.notion.site/HOW-TO-CREATE-OR-JOIN-AN-ON-CHAIN-DAO-24cec19c32ba80d3a0b8d7a711565b4a?source=copy_link
Post link: https://t.me/xdaoapp/1628
My address: UQDWLVQ2hW5tiJ428hluAf_UbTLNp76FlOEJyiKofltD06U0
=> add xdao.json

assets/gaming/battles.json
HEX:
0:287f9ad70e1e8c7c7439ea473597a0e31a8bf72a880f4747904e05a1080d498c
Bounceable: EQAof5rXDh6MfHQ56kc1l6DjGov3KogPR0eQTgWhCA1JjHca
Non-bounceable: UQAof5rXDh6MfHQ56kc1l6DjGov3KogPR0eQTgWhCA1JjCrf
This address is used to cashout Telegram stars from the battles bot:
We can proof this with the factt that it owns collectible usernames used in the project's channel:
Channel:
Bot:
My address: UQDWLVQ2hW5tiJ428hluAf_UbTLNp76FlOEJyiKofltD06U0
=> add new battles label

assets/gaming/tsuefa.json
HEX: 0:fe0324951bfae00eb38621fc6f10a9bf2dcf6f63ce746291cc009edf635f37ff
Bounceable: EQD-AySVG_rgDrOGIfxvEKm_Lc9vY850YpHMAJ7fY183_0sy
Non-bounceable: UQD-AySVG_rgDrOGIfxvEKm_Lc9vY850YpHMAJ7fY183_xb3
My wallet for rewards: UQBqDUtXzQ42H41hDPj9nN9vs7q4zFzhX-rArtIVZ8DOoFai
First, I made an in-game deposit (https://tonviewer.com/transaction/d919b3683b8c4b93626290b7417a19a16a34880d7e19f2e7ae3f3f3fad3a4599) - UQBEZT4W_O2pS50zo_lKbz0-fwj_xzwdEHQhjhBXY2lix19G
After analyzing this address, we can see that the address making the payouts and the one we want to tag (UQD-AySVG_rgDrOGIfxvEKm_Lc9vY850YpHMAJ7fY183_xb3) has comments containing “Withdraw # from bot @tsuefa.” Additionally, looking at the transactions, we can see that funds from the in-game address are often sent to the withdrawal address, …
=> Add Suefa label

assets/merchant/stars_wallet.json
HEX: 0:53f1dbfd2c71fdf19bc768beec9de97cbe534bec673e824de05144e2cbe92f3d
Bounceable: EQBT8dv9LHH98ZvHaL7snel8vlNL7Gc-gk3gUUTiy-kvPR3j
Non-bounceable: UQBT8dv9LHH98ZvHaL7snel8vlNL7Gc-gk3gUUTiy-kvPUAm
My-wallet: UQAbrZ8C6qUAgwfjZXLw54CabmmlL9Rnfem90yOPJ-fYBXbM
This address belongs to - **Stars Wallet**
This wallet often receives TON from an **already marked Stars Wallet address**. It is noteworthy that the transactions are not commented, as usually happens from a marked Stars Wallet.
Also from this wallet we can notice withdrawals to the address (UQBnMbYKh9zj8STivHeGby_oV9Z2K_7FHPP9qVB-rYN0GQhL). From this address all TONs go to the OKX exchange **TON also came to 0GQhL from a marked Stars Wallet address.**
**The main last proof:)**
The address we are investigating …
=> Stars Wallet

assets/gaming/boxingstarx.json
HEX: 0:cf2a0668a377cb23b9f087c9e0816f254ef36ed8cc971f82851024c647269cce
Bounceable: EQDPKgZoo3fLI7nwh8nggW8lTvNu2MyXH4KFECTGRyacznSm
Non-bounceable: UQDPKgZoo3fLI7nwh8nggW8lTvNu2MyXH4KFECTGRyaczilj
My-wallet: UQAbrZ8C6qUAgwfjZXLw54CabmmlL9Rnfem90yOPJ-fYBXbM
**This address belongs to the organization - Boxing Star X**
First, you can pay attention to the latest transfers to the address (UQAJ0UXLab2fQtmWhjpMM-akBtendCMUqXmyioMn2T4zTVUE):
- This wallet also received funds from the organization Boxing Star X;
- All funds were withdrawn to OKX.
The next transfer, which was made from this address, was sent to another Boxing Star X wallet (UQAFQOj2hGqYT2DOkkg9wWYOUTKbBAsfo9pQppguAev0aZUQ):
- Boxing Star X payments were made from this wallet;
- You can also see the signature "**Dev Test"** in this …
=> Boxing Star X

assets/gaming/hypergift.json
HEX:
0:74419de72a24954490a7c4538a79668bf4dfd3787185397d1a015ea49cc321f2
Bounceable: EQB0QZ3nKiSVRJCnxFOKeWaL9N_TeHGFOX0aAV6knMMh8r__
Non-bounceable: UQB0QZ3nKiSVRJCnxFOKeWaL9N_TeHGFOX0aAV6knMMh8uI6
This address receives the proceeds from Telegram Stars cashout and transfers it to two addresses (UQAvA8RbaSt1Vb4g2GBkSeKAtIvl9aiyCDQG8YObRUMFvVLp and UQCi4Yx_0ZJMO5KBTJg63JFUxXDaN_OipLFAJ0iqhqf-tjZw):
Tonviewer reveals that UQAvA8RbaSt1Vb4g2GBkSeKAtIvl9aiyCDQG8YObRUMFvVLp is a disposal address meaning it sends every token it receives to an exchange which is OKX in this case:
Further analysis of transactions shows that UQB6_xW0bYy6qQuzxO6xpbzUCx6fd2tBpse_dC7xGqMJG99K the first address to interact with UQAvA8RbaSt1Vb4g2GBkSeKAtIvl9aiyCDQG8YObRUMFvVLp shows it receiving and then transferring the …
=> add new hypergift
