assets/cex/bitpin.json, assets/cex/gate.io.json, assets/cex/mexc.json
=> add missing CEX wallets

assets/gaming/shakestars.json
0:6B9B722B0A2102986A7EDF5CB5DB48F0620F863D1DF80E7DCE569EE05FABA17D >
EQBrm3IrCiECmGp-31y120jwYg-GPR34Dn3OVp7gX6uhfUbx
My wallet: UQCaSv0HpxKMXYcRoW8nRbSpEaDDff3KdoqN63sKghQ6LRlK
=> add shakestars label

assets/cex/crypto_bot.json
https://tonviewer.com/transaction/54219b428fdc901729316880c097ebb9a7979e592b31d7b9f0f5761e44965add
test withdraw from @send
withdraws are being made from this address
0:EC85CFC7FD1009362E421B5A0141F510D6540107AB73E7829FDA1EF9E97A75E3 > EQDshc_H_RAJNi5CG1oBQfUQ1lQBB6tz54Kf2h756Xp14_Cv
my wallet:
UQCaSv0HpxKMXYcRoW8nRbSpEaDDff3KdoqN63sKghQ6LRlK
=> add new address for crypto_bot

assets/wallet/pocketfi.json
screenshot from DevTools of pocketfi app
0:79eef183870fc12890d6a426795b069856e7b4bef828175ab0fc5fa26ef7bd24 > EQB57vGDhw_BKJDWpCZ5WwaYVue0vvgoF1qw_F-ibve9JETZ
my wallet:
UQCaSv0HpxKMXYcRoW8nRbSpEaDDff3KdoqN63sKghQ6LRlK
=> add new address for pocketfi

assets/dex/stormtrade.json, assets/gaming/catizen.json, assets/gaming/lost_dogs.json, assets/gaming/vanilla_finance.json, assets/liquid_staking/bemo.json, assets/wallet/mytonwallet.json
https://dune.com/okhlopkov/ton-address-finder 
**"Make sure you input a EQ address, not a UQ."**
its not help, bc in wallet i got Non-bounceable address (looks like i get address by my connection in old way)
=> Add storm, lost dogs, vanilla finance, mytonwallet

assets/cex/coinex.json
A new label for **Coinex** has been identified and added as part of the **TON Foundation's side quest**  
**Evidence:**  
- **Source:** Screenshot from [www.coinex.com](https://www.coinex.com/en/asset/deposit?type=TON)  
- **Address (hex):** `0:823bbb10a70167f040e719e99596ec93036ce7bfa3c5c04be2e0d75834749b8b`  
- **Address (bounce):** `EQCCO7sQpwFn8EDnGemVluyTA2znv6PFwEvi4NdYNHSbi8Zy` 
---
- **My Wallet:** `UQBArs50OI7Fo1psjVHIPKoAwCzF-dGmELIuLSrw7ianO9Q9`
- **My TG:** https://t.me/B_E_H_O_L_D
=> feat: Added new label for Coinex

assets/merchant/split.tg.json
1. EQBS114FhHMAASOdTNjHPWUbIG6sZ9tVFTW2ttUF5tQcd-kx
tx example:
https://tonviewer.com/transaction/24cf82a18748625d06b46a869768f8efdb06952bbeeda6037d8462d4748299dc
fee wallet - UQDjwMetsy4eDE98homCP8VAEXIjfy8YyLwomLXELshvtbp1 which is labelled split.tg fee collector wallet
2. EQA0mhGgQXpPijbcqFU9a2tN_rUdfFxF4Ru1XBnwRaN9gfYM
tx example:
https://tonviewer.com/transaction/56ad5e2ce03f61bb3f32a7c33cd2cda447a95bc37be3e54beecca8b71ea2cefd
same fee address
3. EQCHQL4jLYhPNEq_fwaYbmEM_jDpu48G7yEQef4Ur9LzXUrN
tx example:
https://tonviewer.com/transaction/e93642301e1755f5a6dc39a37c204b458117bd1bd13d8bdedfba4d902b355f30
same fee address
=> add 3 more addresses to split.tg

assets/merchant/fragment.json
contest HEX address: 0:80D78A35F955A14B679FAA887FF4CD5BFC0F43B4A4EEA2A7E6927F3701B273C2
Bounceable: EQCA14o1-VWhS2efqoh_9M1b_A9DtKTuoqfmkn83AbJzwnPi
Non-bounceable: UQCA14o1-VWhS2efqoh_9M1b_A9DtKTuoqfmkn83AbJzwi4n
[Link to getGems](https://getgems.io/collection/EQCA14o1-VWhS2efqoh_9M1b_A9DtKTuoqfmkn83AbJzwnPi)
=> Add label for telegram usernames collection address

assets/gaming/gatto.json
HEX: 0:70f1219315d72275925ba4d6af180fb106ae9f19596b03394d593ea5e3c1cfbf
Bounceable: EQBw8SGTFdcidZJbpNavGA-xBq6fGVlrAzlNWT6l48HPv9VE
Non-bounceable: UQBw8SGTFdcidZJbpNavGA-xBq6fGVlrAzlNWT6l48HPv4iB
This contract can be found in game' official docs: https://gatto-game.gitbook.io/gatto-or-whitepaper/version-on-english/rules-and-useful-links/qa
-------
=> Label gatto nft-converting contract

assets/gaming/camelshouse.json
HEX: 0:46ac28aaeaded76eb8077699aa86b19303ad6247ae09df04c91ac69e9f614c9b
Bounceable: EQBGrCiq6t7XbrgHdpmqhrGTA61iR64J3wTJGsaen2FMmzPo
Non-bounceable: UQBGrCiq6t7XbrgHdpmqhrGTA61iR64J3wTJGsaen2FMm24t
It's a claim contract for camelsHouse project
---- 
=> Add label for camelshouse contract

assets/dex/memeslab.json
HEX:0:014237db13750df362f40f2c4d8c724291fcf4aa16a6090191562925c75fc4a6
Bounceable:EQABQjfbE3UN82L0DyxNjHJCkfz0qhamCQGRViklx1_EphOe
Non-bounceable:UQABQjfbE3UN82L0DyxNjHJCkfz0qhamCQGRViklx1_Epk5b
This address is used for fees collection  & sending percentage of fees revenue back to creators
fee on trade is sent to this address
comments on outgoing transactions
-----
=> Create memeslab file & label

assets/merchant/marketapp.json, assets/merchant/tonnel_gift_marketplace.json
HEX:
0:c2baf558c36dd6630fff62c00dd76601f4a38835e570c4a0016e4e409fd2b8fa
Bounceable:
EQDCuvVYw23WYw__YsAN12YB9KOINeVwxKABbk5An9K4-p5y
UQDCuvVYw23WYw__YsAN12YB9KOINeVwxKABbk5An9K4-sO3
Address for minting gifts from Tonnel Gift Marketplace
Resource: https://t.me/tonnel_en/580
https://tonviewer.com/transaction/fe13644c65655ef62168b3700f4a3346cd20db736edc79003e469e30b3927c91
https://tonviewer.com/transaction/29a5ae4b643359296534d6fae6e91123b43ed018af91c973c82db4eab0f76c74
I have also added the website Tonnel Gift Marketplace (market.tonnel.network)
Resource: https://t.me/tonnel_en/637
=> Add Tonnel gift marketplace label

assets/merchant/marketapp.json, assets/merchant/tonnel_gift_marketplace.json
Add marketapp label
New nft deployer contract
HEX:
0:53191a57801de242aef8a4735c9cacc553f4b88f85869ee6ce89860b53924538
Bounceable:
EQBTGRpXgB3iQq74pHNcnKzFU_S4j4WGnubOiYYLU5JFOHwU
UQBTGRpXgB3iQq74pHNcnKzFU_S4j4WGnubOiYYLU5JFOCHR
https://marketapp.ws/nft/EQBYr00Kt65pbQSEE5vQW4Qs33rVeSQ5ldzJKwRx48VPUPyi
Sale contract: https://tonviewer.com/EQDBt5mc_5Cp-qHqKJGBhggQKHPYHZ-4ZKUVjJI4lqYxBRbW
https://marketapp.ws/nft/EQB7GXh3IrSOely_AJBT0BR0o2jKfMWdQW981s8PbZQik-CB
Sale contract: https://tonviewer.com/EQAO69IJlji7XmtNJMDIZPxK-ujh2jP-mDS1Z-IIBQxJUFox
https://tonviewer.com/transaction/1043a64e3361a9ac65b7015748fbad347e73aee56b685dcb7feaa45b9b82d1fa
https://marketapp.ws/nft/EQA5FepzFCj3hRC5D9Et4hVfpUZsFFqGPD79m6C7sN89_ABB/
My address for rewards: …
=> Add Marketapp label

assets/infrastructure/intract.json
HEX: 0:26a27326548de08c1c50784d0340187133bcb5b2643dedd3aad805e515916447
Bounceable: EQAmonMmVI3gjBxQeE0DQBhxM7y1smQ97dOq2AXlFZFkRyTY
Non-bounceable: UQAmonMmVI3gjBxQeE0DQBhxM7y1smQ97dOq2AXlFZFkR3kd
It's a intract protocol wallet for colleting fees
1. First clue was that it had a small number of outgoing transactions, and one recievers had another transaction, referring to it as 'intract deployer'
2. Then I went to the app, and to mint 'proof of humanity', users need to send payment to contract [EQBw…2Tvw](https://tonviewer.com/EQBwCu4Efpf-W9JO5pWHDzLr-RdVYWraiQysk0-pnV_A2Tvw) which then always sends most of cash  to fee collector in question
example transaction -https://tonviewer.com/transaction/732cc1fbcc52ae0425e246c00373896a3f77e319201f341ca258524146c66d3a
---
My address for rewards: …
=> Add label for intract protocol

assets/gaming/major.json
HEX:
0:0AC8E40E91AF1560CF9C9B38850FF76C36E398FCA5D4A25EC4DC2B0A269E3E64
Bounceable:
EQAKyOQOka8VYM-cmziFD_dsNuOY_KXUol7E3CsKJp4-ZFgm
UQAKyOQOka8VYM-cmziFD_dsNuOY_KXUol7E3CsKJp4-ZAXj
This contract belongs to Major, when selling through the nft marketplace in Major WebApp, nft is transferred to it. I suggest you familiarize yourself with my screenshots and the transactions I made for selling nft through their marketplace
My transaction: https://tonviewer.com/transaction/26a2b29d40947b2af5369d3bdcba3025a4c4c58f19f591765a6aafa0c51903d0
My wallet: UQB2tzwFHsjIkXMdVo0GmjjfeZ7XJyI0Oi2C2-pkguF8sGYQ
My tg: @rhexpo
=> add major label

assets/gaming/omega.json
HEX:
0:a606b26b3e5663fae66731e35a6ea1bb2a318017bf4b1ae02b18f0ffa229ae54
Bounceable:
EQCmBrJrPlZj-uZnMeNabqG7KjGAF79LGuArGPD_oimuVL7D
UQCmBrJrPlZj-uZnMeNabqG7KjGAF79LGuArGPD_oimuVOMG
This wallet remains to OMEGA miniapp - @Omega_tonbot.
I tried to make a transaction in @Omega_tonbot and saw the corresponding address and comment. Check out the screenshots:
My wallet: UQB2tzwFHsjIkXMdVo0GmjjfeZ7XJyI0Oi2C2-pkguF8sGYQ
My tg: @rhexpo
=> add omega label

assets/gaming/collection_hunt.json
HEX:
0:4dc9a54d2029f7ff0aec5ed8e0ebd0226b07346612585c6ca66887a6eb078300
Bounceable:
EQBNyaVNICn3_wrsXtjg69Aiawc0ZhJYXGymaIem6weDABXf
UQBNyaVNICn3_wrsXtjg69Aiawc0ZhJYXGymaIem6weDAEga
The address belongs to the game Collection Hunt and is used to receive microtransactions
It's a tap game, and TON microtransactions provide bonuses. I made 2 transactions
https://tonviewer.com/transaction/94daf3b3300d7446e128e5154596992b25099b09d9f1d9b4410be537731587cd
https://tonviewer.com/transaction/bef7db1d4e75138a7601605c5d8ff2206c26fb5586457c7692ccc5ac085dc673
=> Create collection_hunt.json & label

assets/scammer/scammer.json
HEX:
0:08cd39f31bef522a8c6dccd5c4b1b599a41ce2c444ac675528a988fce1bb42fa
Bounceable:
EQAIzTnzG-9SKoxtzNXEsbWZpBzixESsZ1UoqYj84btC-io9
UQAIzTnzG-9SKoxtzNXEsbWZpBzixESsZ1UoqYj84btC-nf4
https://tonviewer.com/0:08CD39F31BEF522A8C6DCCD5C4B1B599A41CE2C444AC675528A988FCE1BB42FA
**Wallet creates void tokens and tries to scam people.**
my wallet: UQAbrZ8C6qUAgwfjZXLw54CabmmlL9Rnfem90yOPJ-fYBXbM
=> add scammer

categories.json
Add a new category to label scripted activity (see #104 and other referenced PRs).
=> add scripted category

assets/gaming/bums.json
Nexusverse also made these projects:
1. Bums
2. Fomo Hash 
3. Giftbox
One we'd have labels from other apps, we can link them to nexusverse. https://www.nexusverse.io/
=> set correct organization name: Nexusverse

assets/bridge/chainconnect.json
HEX: 0:4b6917b8d9357cee4d24a8605d28327108e0dc06b0fe478614a22a27b9c30805
Bounceable: EQBLaRe42TV87k0kqGBdKDJxCODcBrD-R4YUoionucMIBb25
Non-bounceable: UQBLaRe42TV87k0kqGBdKDJxCODcBrD-R4YUoionucMIBeB8
Chainconnect is a bridge, they have a public list of handled transfers https://app.chainconnect.com/transfers
All hamster network -> ton transfer transactions are routed through this address
ccwton (chain connect wrapped ton)
hmstr
----
=> Add label for chainconnect

assets/person/farm2_paws.json, assets/scripted-activity/sybil_EQDByRqo.json
[rebuild](https://github.com/ton-studio/ton-labels/pull/113)
HEX:
[0:c1c91aa87de80e30c17eea9203bb9dd9109f920940b2358a1ac0fd22f2c42ad8](https://tonviewer.com/0:c1c91aa87de80e30c17eea9203bb9dd9109f920940b2358a1ac0fd22f2c42ad8)
Bounceable:
EQDByRqofegOMMF-6pIDu53ZEJ-SCUCyNYoawP0i8sQq2BRs
UQDByRqofegOMMF-6pIDu53ZEJ-SCUCyNYoawP0i8sQq2Emp
This wallet send TON for other wallet for they can make activity in PAWS
https://tonviewer.com/transaction/458e3952ad49c72a3c6063e8d9a5cc6b2337892757493d6234c95c311e296b1c
[Receiver](https://github.com/ton-studio/ton-labels/pull/112#issue-2922517851)
[Sender1](https://github.com/ton-studio/ton-labels/pull/113#issue-2922526408)
[OKX10 got all](https://github.com/ton-studio/ton-labels/pull/115#issue-2922542106)
=> Add labels Farm2 Paws sender

assets/gaming/eton.json
HEX:
0:cea2c578d514b2c2a5b362f2ca712f0fdd08c570e323ecbf8daaee7bf60eef20
Bounceable:
EQDOosV41RSywqWzYvLKcS8P3QjFcOMj7L-Nqu579g7vIJF3
UQDOosV41RSywqWzYvLKcS8P3QjFcOMj7L-Nqu579g7vIMyy
This address belongs to the game ETON and is used to purchase boosts
I made 1 transactions
https://tonviewer.com/transaction/7d6c3a67f7ca35aa2279befb4f178c015b0ff722b1e6c4c22cf4cd54db03522e
=> Create eton.json  & label

assets/scammer/scammer.json
HEX:
0:B59A06005210C43FA89493A4039C448A4C3C79A6F7AABD0EA2BB9C3C250E194E
Bounceable:
EQC1mgYAUhDEP6iUk6QDnESKTDx5pveqvQ6iu5w8JQ4ZTmr1
UQC1mgYAUhDEP6iUk6QDnESKTDx5pveqvQ6iu5w8JQ4ZTjcw
mimic for $PAWS token
=> Add scammer label

assets/gaming/planetswap.json
Tonplanet jetton master accepts messages from this address 
https://tonviewer.com/EQDA5F6kcoXsdtCBZzYQ8mZNg9Ka7-8w7G5UwynaR11A-84H
=> Add tonplanet smart contract

assets/gaming/memhash.json
HEX:
0:1bb579c2ade6184d0bf7d548c8089f207aa95d38f08c16c9fdc2b108290be3ec
Bounceable:
EQAbtXnCreYYTQv31UjICJ8geqldOPCMFsn9wrEIKQvj7HWs
UQAbtXnCreYYTQv31UjICJ8geqldOPCMFsn9wrEIKQvj7Chp
The wallet belongs to Memhash and is used for withdraw $MEMHASH
Made transaction
https://tonviewer.com/transaction/0cdea5a1700f45fa31a76203b8ca9972ef559fb545167937af0eb998d2c45670
=> Add memhash label

assets/gaming/bodypump.json
HEX:
0:8246DAD7AA69FDE6DCEED1ED8E9455B29BD11E56DF5B2E4AC7B9C93F233E5023
Bounceable:
EQCCRtrXqmn95tzu0e2OlFWym9EeVt9bLkrHuck_Iz5QI8JQ
UQCCRtrXqmn95tzu0e2OlFWym9EeVt9bLkrHuck_Iz5QI5-V
The wallet belongs to BodyPump and is used for anti-bot verification
Made transaction
https://tonviewer.com/transaction/ed32f5630c023ace75324e7422b0e0ffa27383cad55941f057eed5b8213b5efa
=> Create bodypump & label

assets/scammer/scammer.json
HEX:
0:ed262e23ce69a78fdabba019a0a2e9d065dfe24ce32838e9bac11891d1f497d3
Bounceable:
EQDtJi4jzmmnj9q7oBmgounQZd_iTOMoOOm6wRiR0fSX03IV
UQDtJi4jzmmnj9q7oBmgounQZd_iTOMoOOm6wRiR0fSX0y_Q
Spam wallet
=> Add label scammer my_tonkeeper

assets/cex/toobit.json
HEX:
0:1A06DEB70A2C3BE1AC32B2759188912ACDC03477F26DFD3752FED20201B3AF50
Bounceable:
EQAaBt63Ciw74awysnWRiJEqzcA0d_Jt_TdS_tICAbOvUCRS
UQAaBt63Ciw74awysnWRiJEqzcA0d_Jt_TdS_tICAbOvUHmX
This wallet belongs to the cryptocurrency exchange Toobit. The wallet receives deposits through intermediary wallets created for users and is also used for withdrawals
I made a deposit of 1, 0.8 TON to the exchange's intermediary wallet, which was later sent to the main wallet (label)
https://tonviewer.com/UQA7Hg-VP-NfS2mZZL5quAcQFslTFCoc3_-8zciJ1zt07XmI
Then, I requested a withdrawal from the exchange to my wallet
https://tonviewer.com/transaction/98510705617a783e7913c7415cbc247803d15f62f936399925de383da477799c
=> Create toobit & label

assets/dex/tradoor.json
source - https://github.com/ton-studio/ton-etl/blob/main/parser/parsers/message/tradoor_trades.py
=> Add tradoor

assets/gaming/dinodrop.json
HEX:
0:F900A810BEEAE33AF6115B2DEC1C048D811725AFE6DE3B43BE6E051D8C5C813E
Bounceable:
EQD5AKgQvurjOvYRWy3sHASNgRclr-beO0O-bgUdjFyBPi1G
UQD5AKgQvurjOvYRWy3sHASNgRclr-beO0O-bgUdjFyBPnCD
The wallet belongs to dinodrop, a CS2 gambling site
The wallet receives deposits through intermediary wallets
Made transaction
https://tonviewer.com/transaction/be3ed1cfd24bc82a24358267029dbe9520ef75f7f3280cb7e6ba4a8b54d61836
=> Create dinodrop & label

assets/gaming/cryptid_hunter.json
HEX: 0:c6d26b87d6beb91fba2e0dfb23aa5f18d2347ac54016aa4717fb0247bc321ee4
Bounceable: EQDG0muH1r65H7ouDfsjql8Y0jR6xUAWqkcX-wJHvDIe5F_k
Non-bounceable: UQDG0muH1r65H7ouDfsjql8Y0jR6xUAWqkcX-wJHvDIe5AIh
Address is hardcoded in miniapp
--- 
=> Add label for cryptid hunter game

assets/gaming/time_ton.json
HEX:
0:70e4166c52853f59d9bba02fb2c1c66c934de1f089fe21818d2ae7b47b42fc6e
Bounceable:
EQBw5BZsUoU_Wdm7oC-ywcZsk03h8In-IYGNKue0e0L8bidk
UQBw5BZsUoU_Wdm7oC-ywcZsk03h8In-IYGNKue0e0L8bnqh
This is old wallet who accept TON from game, same as [here](https://github.com/ton-studio/ton-labels/pull/124)
HEX:
0:9976fba4473dea8a991ee21e60e122a7daa28355751a48089f0df7b1d8f6c076
Bounceable:
EQCZdvukRz3qipke4h5g4SKn2qKDVXUaSAifDfex2PbAds6J
UQCZdvukRz3qipke4h5g4SKn2qKDVXUaSAifDfex2PbAdpNM
this is new wallet for deposite
=> Add wallet for time_ton

assets/gaming/yescoin.json
HEX: 0:a5adbac0a4477ee9918d3f48562f53b148cd967d1d98ba716cd980a535748468
Bounceable: EQClrbrApEd-6ZGNP0hWL1OxSM2WfR2YunFs2YClNXSEaEKy
Non-bounceable: UQClrbrApEd-6ZGNP0hWL1OxSM2WfR2YunFs2YClNXSEaB93
Address is hardcoded in miniapp
And also owns two ton domains, mentioning yescoin
---
=> Add yescoin label

assets/gaming/genki_miner.json
HEX: 0:5cfa76b68667a99984745e830f7b0abf8d6a1e9aa9a8642e4a65b583e22d8de3
Bounceable: EQBc-na2hmepmYR0XoMPewq_jWoemqmoZC5KZbWD4i2N46ES
Non-bounceable: UQBc-na2hmepmYR0XoMPewq_jWoemqmoZC5KZbWD4i2N4_zX
Official game chat has a channel where bot posts users' usdt withdrawals, and they're all handled through this address
[example transaction 
](https://tonviewer.com/transaction/b177f2e86ba28ef0a2f930ed40f8741184a65fa06d949020cd7b6b5e24dcc73d)
---
the second address in PR is used for in-game TON deposits and is hardcoded in miniapp
---
=> Add genkiminer addresses

assets/gaming/tonpoker.json
HEX:
0:3F139E93744A8F4E523CE4323C884436AF2814C2C15B40EECDA5379470BC62A5
Bounceable:
EQA_E56TdEqPTlI85DI8iEQ2rygUwsFbQO7NpTeUcLxipde3
UQA_E56TdEqPTlI85DI8iEQ2rygUwsFbQO7NpTeUcLxipYpy
The wallet belongs to tonpoker. Receives USDT deposits through intermediary wallets
Here is the transaction:
https://tonviewer.com/transaction/c941307ef0df40749dc7edc8f157fc623d8764b04bf39969cce1ae499c7866de
I have also added EQBkh0S7_G_hJ90FweKZqjIglaHodhdba2_zMpck9JrHXLWY
It's a fee Distributor wallet, which distributes 0.07 TON to intermediary wallets for further transfer to the main wallet - (EQA_E56TdEqPTlI85DI8iEQ2rygUwsFbQO7NpTeUcLxipde3)
And added a withdrawal wallet, which has the linked domain tonpoker.t.me
Withdraw transaction: …
=> Add tonpoker label

assets/gaming/kitty_mint.json, assets/scripted-activity/sybil_EQAB_egB.json, assets/scripted-activity/sybil_EQC7zus1.json, models.py
HEX:
0:01fde801481db8a2c660516f56132321c2f99cc8e75cf14b569c22fec8385c9e
Mainnet:
Bounceable:
EQAB_egBSB24osZgUW9WEyMhwvmcyOdc8UtWnCL-yDhcnhkB
UQAB_egBSB24osZgUW9WEyMhwvmcyOdc8UtWnCL-yDhcnkTE
This wallet receives leftovers from other wallets that have activated for the Kitty Mint game.
https://tonviewer.com/transaction/e6565373f1667d0e00f2a7bf476075544ddbdfb10ae818f560be692cf216025e
https://tonviewer.com/UQBrY07ZLUh-ZmW5UITtjRJ7t4xXrqgKnhrj5eS3dUFcQO4U
His second wallet for accumulate DUCK and cashout to OKX-10
HEX:
0:1f85aa8ecbb84e3cf0fb8f4af1ab5ae814b22b25762fe06b41c44983754d29e4
Mainnet:
Bounceable:
EQAfhaqOy7hOPPD7j0rxq1roFLIrJXYv4GtBxEmDdU0p5F6t
UQAfhaqOy7hOPPD7j0rxq1roFLIrJXYv4GtBxEmDdU0p5ANo
https://tonviewer.com/transaction/2a2d3d80a3d614db48d9ea97080 …
=> Add label sybil_EQAB_egB

assets/gaming/goat_gaming.json
HEX:
0:0B5680E1D60F25136567FB822F8A4DA23EABB2F975D11CDCA9CD71229F85C3BA
Bounceable:
EQALVoDh1g8lE2Vn-4Ivik2iPquy-XXRHNypzXEin4XDukVt
UQALVoDh1g8lE2Vn-4Ivik2iPquy-XXRHNypzXEin4XDuhio
The wallet belongs to goat gaming
Made a transaction
https://tonviewer.com/transaction/b63aae3e4fdac02f7400f9bb7c12a92076c4a38fb691c286c6160fe0fc613bb3
=> Create goat_gaming & label

assets/gaming/capybara_meme.json
HEX:
0:74298A385CBFDFE04ADE12D0B6A55188C8DB43255E11DB2F71047B45132C2E94
Bounceable:
EQB0KYo4XL_f4EreEtC2pVGIyNtDJV4R2y9xBHtFEywulCYf
UQB0KYo4XL_f4EreEtC2pVGIyNtDJV4R2y9xBHtFEywulHva
The wallet belongs to Capybara MEME
Made a transaction
https://tonviewer.com/transaction/40e8e6ecde3dc87a67bcf1edba0334dc9257bf80b1bb62c9b82730cc908acd58
Added another game wallet (EQCN_n8QT3zEl-rnqzVR3c_v7y9OY2Q5mSDDkqubfNluHd7a)
Made a transaction
https://tonviewer.com/transaction/da944ef39dfc66bee38e0efe8ec705aac7e872e2de32a2d347b809a1e9d5cfc4
=> Create capybara_meme & label

assets/scammer/scammer.json
HEX: 0:e03c13d765862b92754fb9db4be8f1526aff8c727e9ffd43c389c2c3f1f41da7
Bounceable: EQDgPBPXZYYrknVPudtL6PFSav-Mcn6f_UPDicLD8fQdp1hf
Non-bounceable: UQDgPBPXZYYrknVPudtL6PFSav-Mcn6f_UPDicLD8fQdpwWa
Scammer bought a stonfi-like tg domain and mass sending spam transactions
---
=> Add scammer address

assets/cex/okx.json
[OKX-10](https://github.com/ton-studio/ton-labels/pull/115#issue-2922542106) [UQBmoechltZNb69I-ksuqGH2ewSE0tFKWcr3AdjChs5E5Uii](https://tonviewer.com/UQBmoechltZNb69I-ksuqGH2ewSE0tFKWcr3AdjChs5E5Uii)
OKX-11
HEX:
0:47db0fc205b77548e9e6d15eaf01ab0743c945cc9925077f018a21cd450ffd85
Mainnet:
Bounceable:
EQBH2w_CBbd1SOnm0V6vAasHQ8lFzJklB38BiiHNRQ_9hXWf
UQBH2w_CBbd1SOnm0V6vAasHQ8lFzJklB38BiiHNRQ_9hSha
https://tonviewer.com/transaction/389a553cf21af8962ea40f561be2f56a85dd57fbe7611a135105aa6208558d3a
OKX-12
HEX:
0:1cccebbe0e89b96432673390a7c23465d1e137985b16ab1f5ea4b56017fec02e
Mainnet:
Bounceable:
EQAczOu-Dom5ZDJnM5CnwjRl0eE3mFsWqx9epLVgF_7ALrTu
UQAczOu-Dom5ZDJnM5CnwjRl0eE3mFsWqx9epLVgF_7ALukr
USDT move to OKX-13 …
=> Add label OKX wallets

assets/dex/ston.fi.json, assets/gaming/rocketrush.json, assets/gaming/tonstation.json, assets/gaming/xstar_fleet.json, assets/liquid_staking/ton_whales.json, assets/liquid_staking/tonstakers.json
Ton Whales addresses were taken from their website API:
=> WIP: Add various labeles

assets/merchant/fragment.json, assets/merchant/getgems.json, assets/merchant/gifton_market.json, assets/merchant/giftpot.json, assets/merchant/marketapp.json, assets/merchant/nest.json, assets/merchant/otcelf.json, assets/merchant/tonnel_gift_marketplace.json, assets/merchant/wts.json, assets/scammer/camelshouse.json, assets/tradingbot/dtrade.json, build_assets.py, models.py, tags.json
This is how it looks like after running `python build_assets.py`.
=> Add "name" field with human-readable string

assets/scammer/scammer.json
HEX:
0:d88d4e0bd3bd6d8434df8ae0b8d4e250f98b9b9e0042cbb64a2a49e6fa714f04
Bounceable:
EQDYjU4L071thDTfiuC41OJQ-YubngBCy7ZKKknm-nFPBAlr
UQDYjU4L071thDTfiuC41OJQ-YubngBCy7ZKKknm-nFPBFSu
Spam ton-airdrops reward sender for scam
https://tonviewer.com/EQDYjU4L071thDTfiuC41OJQ-YubngBCy7ZKKknm-nFPBAlr
Wallet for reward:
=> add label Spam scammer

assets/gaming/tonstation.json
HEX: 0:d16fbddc05277926db1270f36f4724b1aaf64ce2ee8f765759f3df469e87eba6
Bounceable: EQDRb73cBSd5JtsScPNvRySxqvZM4u6PdldZ899Gnofrpu25
Non-bounceable: UQDRb73cBSd5JtsScPNvRySxqvZM4u6PdldZ899GnofrprB8
The address is hardcoded in config inside tonstation app
---
=> Add tonstation staking address

assets/gaming/bombcrypto.json
HEX:
0:2A9D40A3A79CC85BFA02CCF8E526821C1A590071CFE3FFD7EDCC00B05C868247
Bounceable:
EQAqnUCjp5zIW_oCzPjlJoIcGlkAcc_j_9ftzACwXIaCR8ky
UQAqnUCjp5zIW_oCzPjlJoIcGlkAcc_j_9ftzACwXIaCR5T3
https://getgems.io/bombcrypto
Wallet for reward: EQCCYJ-maTvVVdAHRhc10LLd2jiN19meUYgzGPYByOveSwcD
=> Add bombcrypto label

assets/gaming/furydefender.json
HEX:
0:de4c74b312828adff80536c46ee646f3aec260c55a019676887aa63107cf2eee
Bounceable:
EQDeTHSzEoKK3_gFNsRu5kbzrsJgxVoBlnaIeqYxB88u7l0E
UQDeTHSzEoKK3_gFNsRu5kbzrsJgxVoBlnaIeqYxB88u7gDB
Wallet for reward:
=> Add-labels-Fury-Defender

assets/gaming/regalisland.json
HEX: 0:3a395ac39f2cea5fb01f31a429aec662a953dab74a1676dcefc359afc807c50d
Bounceable: EQA6OVrDnyzqX7AfMaQprsZiqVPat0oWdtzvw1mvyAfFDRW8
Non-bounceable: UQA6OVrDnyzqX7AfMaQprsZiqVPat0oWdtzvw1mvyAfFDUh5
Address is sending small amounts of ton with memo 'regal island'
Users in official miniapp chat share screenshots of successful withdrawals coming from this addres
---
=> Add regalisland address

assets/gaming/tokencarnival.json
HEX:
0:1F3D997B306B6C32AFE7458E94C9E5A1F5ED2AB3C563E53A0E70223EBD33EF33
Bounceable:
EQAfPZl7MGtsMq_nRY6UyeWh9e0qs8Vj5ToOcCI-vTPvM6Gj
UQAfPZl7MGtsMq_nRY6UyeWh9e0qs8Vj5ToOcCI-vTPvM_xm
The wallet belongs to Token Carnival game/roulette
Made a transaction
https://tonviewer.com/transaction/379e8e8754f74d99882437c231afeb48f991a7ff5a53f0de322a1057c70f367e
=> Create tokencarnival & label

assets/scammer/scammer.json
HEX:
0:8395a42745576a662caadd207db6f35d2829c1e505c9a17e97092b0f3cc708c6
Bounceable:
EQCDlaQnRVdqZiyq3SB9tvNdKCnB5QXJoX6XCSsPPMcIxqFL
UQCDlaQnRVdqZiyq3SB9tvNdKCnB5QXJoX6XCSsPPMcIxvyO
his previously tokens same scam
https://tonviewer.com/transaction/a89d9dc6bf37f2acdfb73356c2c4aa1ab108a3f8420c855877983e5c1759022f
=> add label scammer USD1 EURC

assets/gaming/cats.json
HEX:
0:DA08E9DD728815FFFFCDF0B7E2B2FE5F83C152B6050C79F0D59B6E4E5CC5A5BB
Bounceable:
EQDaCOndcogV___N8Lfisv5fg8FStgUMefDVm25OXMWlu_eb
UQDaCOndcogV___N8Lfisv5fg8FStgUMefDVm25OXMWlu6pe
The wallet belongs to Cats
Made a transaction
https://tonviewer.com/transaction/b2b3e2864ad5679cf69ed32d259d24b9b3f3e6b1ca0d19df58d41277d97bb47f
=> Add cats label

assets/gaming/time_ton.json
HEX:
0:f756427e298f699eadc281f340f54db91bbebbe7b9e3d5752d4b4784fc137c5c
Mainnet:
Bounceable:
EQD3VkJ-KY9pnq3CgfNA9U25G76757nj1XUtS0eE_BN8XNdN
UQD3VkJ-KY9pnq3CgfNA9U25G76757nj1XUtS0eE_BN8XIqI
This is same type deposite address, project always change wallet
https://github.com/ton-studio/ton-labels/pull/176#issue-2936351233
New deposite wallet
HEX:
0:4d16912af91bc61ba08efacdb10ffa0753acf1635a7819a3469ede2214cc38b5
Bounceable:
EQBNFpEq-RvGG6CO-s2xD_oHU6zxY1p4GaNGnt4iFMw4tQ_j
UQBNFpEq-RvGG6CO-s2xD_oHU6zxY1p4GaNGnt4iFMw4tVIm
=> add label Time Ton

assets/gaming/tonstation.json
Giveaway results in TON Station channel — https://t.me/tonstationgames/489
Comment on transaction:
List of winners, where every receiver addresses can be found: https://docs.google.com/spreadsheets/d/1AVeBXqVW4hOpskY4tyPvC3f7aljB2Lewca_LsXVmx4I/edit?gid=287434408#gid=287434408
Address on dune:
[0:8D5FD7717FC6730627D910BBBDFE98C249884BA91F40EA46C6133B6098B7BF4B](https://tonviewer.com/0:8D5FD7717FC6730627D910BBBDFE98C249884BA91F40EA46C6133B6098B7BF4B)
My address: UQCaSv0HpxKMXYcRoW8nRbSpEaDDff3KdoqN63sKghQ6LRlK
=> new address for tonstation

assets/gaming/voxel.json
HEX:
0:1C347B7259E57602962678306C2705A58C852B0E5DFEB01E71EC1ABC904CEE20
Bounceable:
EQAcNHtyWeV2ApYmeDBsJwWljIUrDl3-sB5x7Bq8kEzuIFS3
UQAcNHtyWeV2ApYmeDBsJwWljIUrDl3-sB5x7Bq8kEzuIAly
This wallet belongs to the game Voxel and uses intermediary wallets for deposits
Made a transaction: https://tonviewer.com/UQBhwu5zOiLeX4DRhaqLoTd6-OZ8HMOeseCcRiv0BBkOzlz3
=> Create voxel & label

assets/gaming/dinodrop.json
HEX:
0:c903536fe213721f95bac384023d0eb12b146d149f14aabec8caef06a06a8a71
Bounceable:
EQDJA1Nv4hNyH5W6w4QCPQ6xKxRtFJ8Uqr7Iyu8GoGqKcbbC
UQDJA1Nv4hNyH5W6w4QCPQ6xKxRtFJ8Uqr7Iyu8GoGqKcesH
When we deposite balance on game, we got address for it
This is temporary service wallet, they recieve and sent to main wallet 
https://tonviewer.com/EQDozkNLsgDPHA_x3RTmMQRMo0ZIjDUWegJ6itTD2CJX9X5Q
=> add label dinodrop

assets/bridge/intersoon.json
HEX:
0:a6a703e6b80ee14aef7d21048c903698952a0490f6cbdf06f8d98a9c530fcdab
Bounceable:
EQCmpwPmuA7hSu99IQSMkDaYlSoEkPbL3wb42YqcUw_Nq5AB
UQCmpwPmuA7hSu99IQSMkDaYlSoEkPbL3wb42YqcUw_Nq83E
https://tonviewer.com/0:A6A703E6B80EE14AEF7D21048C903698952A0490F6CBDF06F8D98A9C530FCDAB
New wallets related intersoon, they dubled transactions, all of them connected between and intersoon
HEX:
0:f9908511997224cb268b58984e6c2b201e915e0f3362cb5f907ce2051d9ae7b6
Mainnet:
Bounceable:
EQD5kIURmXIkyyaLWJhObCsgHpFeDzNiy1-QfOIFHZrntg8n
UQD5kIURmXIkyyaLWJhObCsgHpFeDzNiy1-QfOIFHZrntlLi
HEX:
0:4e5683c6d10de18a3ceec787c6e299c05edba8cfb177cf8348b28f5086968a10
Mainnet:
Bounceable:
EQBOVoPG0Q3hijzux4fG4pnAXtuoz7F3z4NIso9QhpaKEI4s …
=> add label Intersoon

assets/liquid_staking/kton.json, assets/liquid_staking/tonstake.json
HEX:
0:e299dd4ae2bdf788f723eddfe699a8d302841d049c208767a6949a19f6880829
Bounceable:
EQDimd1K4r33iPcj7d_mmajTAoQdBJwgh2emlJoZ9ogIKUhf
UQDimd1K4r33iPcj7d_mmajTAoQdBJwgh2emlJoZ9ogIKRWa
This sub wallet used for Withdraw From TonStake.com 
Activeted by Uf_AhqqheA-GkmwN4uAg7j5qjHffA2VL-kzFuXoYs9fD7h-O
https://tonviewer.com/Uf_AhqqheA-GkmwN4uAg7j5qjHffA2VL-kzFuXoYs9fD7h-O
Now TonStake Successful Transition to KTON https://kton.io/
=> add new label KTON (Ton stake)

assets/gaming/duck_master.json
TODO: 
1. Add proofs
2. My TON wallet address for reward
=> Add Duck Master Address

assets/gaming/Global Ton.json, assets/gaming/Global_Ton.json
HEX: 0:60e1c2c853dd7d0681e974cba13abbf05041aa5a2d1504ed26f130405cac9a5d
Bounceable:
EQBg4cLIU919BoHpdMuhOrvwUEGqWi0VBO0m8TBAXKyaXfP3
UQBg4cLIU919BoHpdMuhOrvwUEGqWi0VBO0m8TBAXKyaXa4
My Wallet: UQBicUiXrZqxzPExSjw4UP4a4ltFscS-cX50SeLj4_eZ-4uN
this address is used by this bot: (@Global_TON_bot)
https://tonscan.org/tx/taBpLm9fkVEGUTnwMGMNpF/sKrRmj0Q1F5TyBKNN2OM= (this is the transaction)
and if you go to it, it will correspond to the address provided in the task
=> global ton

assets/gaming/spinrush.json
HEX: 0:72015b5b2a9b7aead3a11f7078dd1f92850e5f53c5871039165bf0aa7c69a5ee
Bounceable: EQByAVtbKpt66tOhH3B43R-ShQ5fU8WHEDkWW_CqfGml7qW5
Non-bounceable: UQByAVtbKpt66tOhH3B43R-ShQ5fU8WHEDkWW_CqfGml7vh8
---
=> Add spinrush label

assets/gaming/xworld.json
HEX: 0:7ba9dbd5e88d801748581349dadc9ccc8e3fd0caed963e08b24090d239bf34c0
Bounceable: EQB7qdvV6I2AF0hYE0na3JzMjj_Qyu2WPgiyQJDSOb80wL30
Non-bounceable: UQB7qdvV6I2AF0hYE0na3JzMjj_Qyu2WPgiyQJDSOb80wOAx
I made two transactions within the app, deposit & withdrawal: 
Here're corresponding TON transactions: 
[deposit](https://tonviewer.com/transaction/347078355246b1c964a195faaef24bf18d9105892307f58addf2610df3d62582) 
[withdrawal](https://tonviewer.com/transaction/25b12a35f34bf069fe6e792ec19755aad9e3593af606a41dd78ada271802766f) 
---
=> Add xworld labels

assets/gaming/tonbitcoin.json
HEX:
0:12A7F0A9344A0523E1EF4EEAE1EF8353C5D57FBEE5C619DD4FCEC26C8A79C98D
Bounceable:
EQASp_CpNEoFI-HvTurh74NTxdV_vuXGGd1PzsJsinnJjRTs
UQASp_CpNEoFI-HvTurh74NTxdV_vuXGGd1PzsJsinnJjUkp
The wallet holds 98% of the kW token supply, performs minting, and frequently funds the tonbitcoin wallet, which is already labeled
It’s also the wallet that originally minted the entire token supply
I can also add the wallet the team uses to burn tokens
https://tonviewer.com/UQA1yfxD2yVTu_1QMycifyLMOhJoY_BiJBktI_dAeFjYHLid
=> Add tonbitcoin label

assets/gaming/kitty_mint.json
HEX:
0:d96887292d8814d3dd57e32c9b8784689577167dd4e411b31b1660740009c376
Bounceable:
EQDZaIcpLYgU091X4yybh4RolXcWfdTkEbMbFmB0AAnDdkJi
UQDZaIcpLYgU091X4yybh4RolXcWfdTkEbMbFmB0AAnDdh-n
HEX:
0:1644abf534f2f511b1eb0a2a0aa63584655d4923c130f9567d891b5796b90622
Bounceable:
EQAWRKv1NPL1EbHrCioKpjWEZV1JI8Ew-VZ9iRtXlrkGIh-n
UQAWRKv1NPL1EbHrCioKpjWEZV1JI8Ew-VZ9iRtXlrkGIkJi
HEX:
0:a247809fc28b41003a73b26fdc62ee293618567776cb41e861375b59b7767fb7
Bounceable:
EQCiR4CfwotBADpzsm_cYu4pNhhWd3bLQehhN1tZt3Z_t-HS
UQCiR4CfwotBADpzsm_cYu4pNhhWd3bLQehhN1tZt3Z_t7wX
All three wallets were funded from the address kitty_mint (850C869CF8B6FC4BF9E1E8BE70D49B5EA2EFFA3F8CA6383058BE8F05E844688B)
Made a transactions
https://tonviewer.com/transaction/de814944ba1b9c4ae07fff5cec7 …
=> Add kitty_mint labels

assets/cex/okx.json
HEX:
0:e0c17e6eef0eecd033725d5e00a41cb1961770a7ac731981e968ed465aa676a9
Bounceable:
EQDgwX5u7w7s0DNyXV4ApByxlhdwp6xzGYHpaO1GWqZ2qZwH
UQDgwX5u7w7s0DNyXV4ApByxlhdwp6xzGYHpaO1GWqZ2qcHC
=> add label OKX

assets/cex/wallet_in_telegram.json
HEX:
0:582E5DC9E972AA4C60944758BBA6659D3D5C86A24191398E0FB8C023AF553374
Bounceable:
EQBYLl3J6XKqTGCUR1i7pmWdPVyGokGROY4PuMAjr1UzdKVm
UQBYLl3J6XKqTGCUR1i7pmWdPVyGokGROY4PuMAjr1UzdPij
https://tonviewer.com/UQC-V1qHZbTmXbEkVxQXb_nTsdjY0pb2iTxRmUcqXskQ-fJl
Made a transaction: https://tonviewer.com/transaction/c8b9bffd64b52ffd8071aa5e2195abd4f2621ef0436c76b48a9a15489c6913f0
=> Add wallet_in_telegram label

assets/scripted-activity/bigpump.json, assets/scripted-activity/sybil_EQAU0QJF.json
HEX:
0:2ed2a8df730b37139491b65ffa978d355284a9be185ac9c622bce4dd61f78299
Bounceable:
EQAu0qjfcws3E5SRtl_6l401UoSpvhhaycYivOTdYfeCmYMp
UQAu0qjfcws3E5SRtl_6l401UoSpvhhaycYivOTdYfeCmd7s
Wallet where funds are stored. Periodically sent to disposable wallets for token deployment. Then the funds are returned back
Funds were sent to a new wallet and then returned back
Another disposable wallet
Deployed token that no one was interested in (no one bought it), as usual
Proof that it's bigpump
My address: UQDPYJUXtFq6a5GpP4OJ1hphjxfxRbbbhRCqWLGumHd9XbGi
=> Add bigpump sybil address

assets/merchant/0xprocessing.json
HEX:
0:0517A4DFFE30004D36A3FA1B358AB7993AF7DD3FB6CBF31E1F1D698CDF6C2F3F
Bounceable:
EQAFF6Tf_jAATTaj-hs1ireZOvfdP7bL8x4fHWmM32wvP-G5
UQAFF6Tf_jAATTaj-hs1ireZOvfdP7bL8x4fHWmM32wvP7x8
0xProcessing is a cryptocurrency payment gateway that allows businesses and individuals to accept crypto payments on websites, online stores, and other platforms
https://docs.0xprocessing.com/faq
=> Create 0xprocessing & label

assets/gaming/gameofstonks.json
HEX: 0:59d30265b0dce8a3bd9543daf45d7b2b8b8e3a3df1917d224927b349e3161906
Bounceable: EQBZ0wJlsNzoo72VQ9r0XXsri446PfGRfSJJJ7NJ4xYZBkD5
Non-bounceable: UQBZ0wJlsNzoo72VQ9r0XXsri446PfGRfSJJJ7NJ4xYZBh08
Address is hardcoded in miniapp
---
=> Add stonks bot label

assets/gaming/void.json
HEX:
0:c7199f72d107a2b3f9b1f8816aaa850705a04f19796f9bf4ef02441b1016312a
Bounceable:
EQDHGZ9y0Qeis_mx-IFqqoUHBaBPGXlvm_TvAkQbEBYxKnss
UQDHGZ9y0Qeis_mx-IFqqoUHBaBPGXlvm_TvAkQbEBYxKibp
This PR adds @VoidNotHereBot (new game of notcoin team) to the list of games.
my wallet address for reward:
=> add void game

assets/cex/kraken.json
HEX:
0:5D9C2205661CD26552FE17DE8A12CAEECD459F0653C760287F5818A0F795A84A
Bounceable:
EQBdnCIFZhzSZVL-F96KEsruzUWfBlPHYCh_WBig95WoSuNE
UQBdnCIFZhzSZVL-F96KEsruzUWfBlPHYCh_WBig95WoSr6B
The wallet belongs to the Kraken exchange and is used for deposits via intermediary wallets and for withdrawals
Deposit https://tonviewer.com/transaction/e3cadf740eec37bcb471fc857f8bbdb6e3051b07e79c971481096f3992c2270e
Withdraw https://tonviewer.com/transaction/5d27538f6bd51b030706bab7e2b29b3ac0fb606a3940dfed15dc0b9b9d5aadb6
=> Create kraken & label

assets/cex/excoino.json
HEX:
0:934da74461f694352c8e072f565cbe1264e3646e3d20520f9842226b4c06a783
Bounceable:
EQCTTadEYfaUNSyOBy9WXL4SZONkbj0gUg-YQiJrTAang7PB
UQCTTadEYfaUNSyOBy9WXL4SZONkbj0gUg-YQiJrTAang-4E
This PR adds [www.excoino.com](https://www.excoino.com) to the list of exchanges.
excoino is a cryptocurrency exchange based in Iran.
my wallet address:
=> add excoino exchange

assets/scammer/scammer.json
HEX:
0:467D01A9E2103B7FDCD77CF9467CFA0B1580BC0B2EDF8E06C86873886E5A52C8
Bounceable:
EQBGfQGp4hA7f9zXfPlGfPoLFYC8Cy7fjgbIaHOIblpSyHGk
UQBGfQGp4hA7f9zXfPlGfPoLFYC8Cy7fjgbIaHOIblpSyCxh
HEX:
0:D3DBDE8BFF33D8C9C517FE3E07397BB8E2889B8831AB4A8F4112EAD7B38ED32B
Bounceable:
EQDT296L_zPYycUX_j4HOXu44oibiDGrSo9BEurXs47TK0BK
UQDT296L_zPYycUX_j4HOXu44oibiDGrSo9BEurXs47TKx2P
=> Add scammer labels

assets/gaming/pandafit.json
HEX:
0:89377d334e77ab890981dd864838594dc9fab1d1d7767551c83240621b627b6a
Bounceable:
EQCJN30zTneriQmB3YZIOFlNyfqx0dd2dVHIMkBiG2J7aljB
UQCJN30zTneriQmB3YZIOFlNyfqx0dd2dVHIMkBiG2J7agUE
my wallet address for reward:
This PR adds @PandaFiT_bot to the list of games.
=> add pandafit game.json

assets/dex/ston.fi.json
Hex: 0:d1fb8c448e8ea1df2f0191275d2dd625a5d948c2633ece1ab9a7a0349252650f  
Bounceable: EQDR-4xEjo6h3y8BkSddLdYlpdlIwmM-zhq5p6A0klJlD6T0  
Non-bounceable: UQDR-4xEjo6h3y8BkSddLdYlpdlIwmM-zhq5p6A0klJlD_kx  
---
Most outbound transactions from this address contain specific reward-related payloads such as:
- `"Stonbassador Reward for March! Keep Up Your Great Work!"`  
- `"Referral Bonus! Invite more Stonbassadors and support current invitees to have more bonuses!"`
These messages strongly indicate participation in the **[Stonbassadors Program](https://ston.fi/stonbassadors)** — STON.fi’s official ambassador initiative.
---
Other transactions from this address interact with the following verified NFT contract:
🔗 [EQDOt5LNOAADD2wN4ZHHai9IioTrhrUKDgkR_lN3ILqkPaWw](https://tonviewer.com/EQDOt5LNOA …
=> Ston.fi Stonbassador Wallet

assets/gaming/battlebulls.json
HEX: 0:f33b8634407d533fec7af550512fdf003d796c7cd1923329f739184dd7c341cc
Bounceable: EQDzO4Y0QH1TP-x69VBRL98APXlsfNGSMyn3ORhN18NBzBX5
Non-bounceable: UQDzO4Y0QH1TP-x69VBRL98APXlsfNGSMyn3ORhN18NBzEg8
My wallet: UQBPvTVcmD3IU7KAMiVx6DIa2d-8-LIzLHQlLsUE7MMA4FKa
Proof:
@battle_games_com_bot
if you navigate from this mini app you will be taken to this community channel outside of which the token (BBGT) is mentioned in connection with the transfer to the ton network
https://t.me/battle_games_com/605
https://tonviewer.com/UQDzO4Y0QH1TP-x69VBRL98APXlsfNGSMyn3ORhN18NBzEg8
=> battlebulls

assets/gaming/ton_miner.json
HEX:
0:47B56972F6B1006982D92115EE3F872219D3AA3FCB21B14B8EFD756CFBFC6963
Bounceable:
EQBHtWly9rEAaYLZIRXuP4ciGdOqP8shsUuO_XVs-_xpY3Tq
UQBHtWly9rEAaYLZIRXuP4ciGdOqP8shsUuO_XVs-_xpYykv
The wallet belongs to the ton miner game and is used for deposits via intermediary wallets
https://tonviewer.com/UQC6yzAC3Dm3sfNT4joNd25AAlcukEPeNY8_0Z_Udv-EParD
Made a transaction: https://tonviewer.com/transaction/5b816884913b879e5b13e2f6b093e9b18eae72921e5df1e9188e31003efa8260
=> Create ton_miner & label

assets/gaming/wcoin.json
HEX: 0:7a9967e93e454da7242a40ce676b65e02a4b6cb59831fc7013525e660267d6c1
Bounceable: EQB6mWfpPkVNpyQqQM5na2XgKktstZgx_HATUl5mAmfWwed4
Non-bounceable: UQB6mWfpPkVNpyQqQM5na2XgKktstZgx_HATUl5mAmfWwbq9
---
=> Add wcoin label

assets/gaming/starriser.json
HEX:
0:ad094ca1d602255ef5a89082e88096280cdd072db74d0be6ef0205a4074d9561
Bounceable: EQCtCUyh1gIlXvWokILogJYoDN0HLbdNC-bvAgWkB02VYTCe
Non-bounceable: UQCtCUyh1gIlXvWokILogJYoDN0HLbdNC-bvAgWkB02VYW1b
This address is used to make payments when purchasing in-game items in Starriser:
Proof:
=> Add label starriser

assets/scammer/scammer.json
HEX:
0:724055668162b60cc9e5a4260689ee5c5bf058583097b612c475ea408675f8a1
Bounceable: EQByQFVmgWK2DMnlpCYGie5cW_BYWDCXthLEdepAhnX4oU_q
Non-bounceable: UQByQFVmgWK2DMnlpCYGie5cW_BYWDCXthLEdepAhnX4oRIv
This address spams transactions with the message "🎁200TON reward..." and it also has a collectible username (tonkeeper_airdrop) which indicates a pure scam:
My address: UQDWLVQ2hW5tiJ428hluAf_UbTLNp76FlOEJyiKofltD06U0
=> add new scammer

assets/merchant/yarunin.json, assets/other/yarunin.json
HEX: 0:f663f6794d1161dbfa8eb00b87c53d5dee90ece47c74314981f414e5e636f513
Bounceable: EQD2Y_Z5TRFh2_qOsAuHxT1d7pDs5Hx0MUmB9BTl5jb1E-Y7
Non-bounceable: UQD2Y_Z5TRFh2_qOsAuHxT1d7pDs5Hx0MUmB9BTl5jb1E7v-
My address: UQAJ4ELQlXE5Ap3TfYUTKOEReR6EBMUrd38-A-_j8aLXTXFC
---
This address belongs to the **YARUNIN** project, a token-selling operation running a structured sales model with fixed pricing and a 10-year roadmap (🤷‍♂️ atleast that's what  [[their whitepaper says] (https://assets.zyrosite.com/YbNBgXL0kztNpWQ6/whitepaper-en-mP4Oz89Lw9swMR43.pdf)](https://assets.zyrosite.com/YbNBgXL0kztNpWQ6/whitepaper-en-mP4Oz89Lw9swMR43.pdf)).
---
Address found on [website](https://yarunin.com/direct-sale) too
It handles direct sales of the YRN token via their website and STON.fi DEX, with payment flows tied …
=> Add yarunin address

assets/cex/okx.json
Hex: 0:f9ddff100348f7e287a1288d8fc139ec191f2e4a26badcdd8fd9971aabdef92d
Bounceable: EQD53f8QA0j34oehKI2PwTnsGR8uSia63N2P2Zcaq975LSv3
Non-bounceable: UQD53f8QA0j34oehKI2PwTnsGR8uSia63N2P2Zcaq975LXYy
My wallet address:
This address is listed under the OKX project adapter in DefiLlama’s official GitHub repository. (https://github.com/DefiLlama/DefiLlama-Adapters/blob/49af7bda62c525d840c687ee050a7153a03c5ac7/projects/okex/index.js#L528)
plus have made large-value transaction with known addresses associated with OKX:
UQBmoechltZNb69I-ksuqGH2ewSE0tFKWcr3AdjChs5E5Uii
UQBQAGSnFqLxvMV-PXzPH1_hmPDDjG5mhxp4ZABEBKz_cm8D
https://tonviewer.com/transaction/P4QreARuFbZ0tF0L5mQM66esw3RQ6bVS9PHPCZvpMeI%3D …
=> Add OKX wallet

assets/gaming/dreamstation.json
HEX:
0:788996b8fea0efe9d241b13edf6ecb23ba6693d8767c5a1e369d26c0005ee346
Bounceable: EQB4iZa4_qDv6dJBsT7fbssjumaT2HZ8Wh42nSbAAF7jRqxk
Non-bounceable: UQB4iZa4_qDv6dJBsT7fbssjumaT2HZ8Wh42nSbAAF7jRvGh
This address is deposit address for DreamStation
Proof:
My address: UQDWLVQ2hW5tiJ428hluAf_UbTLNp76FlOEJyiKofltD06U0
=> Add label dreamstation

assets/scripted-activity/sybil_bountybay_EQC4gyDn.json
HEX:
0:b88320e7476b48d4df5532e607aca75900a22c1d4c653649bb76efb422679f72
Bounceable:
EQC4gyDnR2tI1N9VMuYHrKdZAKIsHUxlNkm7du-0ImefcjVz
UQC4gyDnR2tI1N9VMuYHrKdZAKIsHUxlNkm7du-0Imefcmi2
my wallet address:
This address sends 0.017 TON to each wallet in order to execute the BountyBay check-in smart contract.
proof:
The address `EQAzIUFN8MJ3cGQiKBqHr-COHAz0D7fNnCD2kHneJxmK9gPd` is a smart contract for check-in on BountyBay:
dune dashboard:
=> add sybil_bountybay_EQC4gyDn

assets/gaming/0xiceberg.json
HEX: 0:ea31bd24d7b875c1f11d9ca87da30c739dbdf82406bef2b326e787ee38dbb175
Bounceable: EQDqMb0k17h1wfEdnKh9owxznb34JAa-8rMm54fuONuxdcEW
Non-bounceable: UQDqMb0k17h1wfEdnKh9owxznb34JAa-8rMm54fuONuxdZzT
---
This address is hardcoded in the Telegram mini app [[@IcebergAppBot](https://t.me/IcebergAppBot)](https://t.me/IcebergAppBot).
---
**My wallet for rewards**: UQBrxUSFqlZZprC3i41UCUAhggkbX1GrLxCl7lALZ0Rnkv0V
=> Add address for 0xiceberg.json

assets/gaming/not_pixel.json
HEX: 0:1212165f4d6b6e23af34d6fd6d90e264306aebe72ca72c6f1c93b3ae13f2ae91
Bounceable: EQASEhZfTWtuI6801v1tkOJkMGrr5yynLG8ck7OuE_KukX5t
Non-bounceable: UQASEhZfTWtuI6801v1tkOJkMGrr5yynLG8ck7OuE_KukSOo
---
=> Add notpixel NFT collection

assets/gaming/forton.json
HEX: 0:2f26e1259f494ff1cd98319e2c286c1046dfe49b1982e3de2ff18e134c780e6a
Bounceable: EQAvJuEln0lP8c2YMZ4sKGwQRt_kmxmC494v8Y4TTHgOasKJ
Non-bounceable: UQAvJuEln0lP8c2YMZ4sKGwQRt_kmxmC494v8Y4TTHgOap9M
It's a deposit address in forton app
---
HEX: 0:988d747ab44727200870e1ee9ac42ce5a8ed73cb3167927cb9e7a670033269a8
Bounceable: EQCYjXR6tEcnIAhw4e6axCzlqO1zyzFnkny556ZwAzJpqGR9
Non-bounceable: UQCYjXR6tEcnIAhw4e6axCzlqO1zyzFnkny556ZwAzJpqDm4
This address is a fee collector from transactions, triggered by the the first contract
1. It's present in all ...asKJ contract transactions ([1](https://tonviewer.com/transaction/c77eded05b9a86b1a2dcaff64d250eb57e41eae1064286d9c967e85b713de6a7), [2](https://tonviewer.com/transaction/5bf8b6c9d0d8c2a3747fa66672393797ff8b987c807ed1b77d17ed2b4f7c0746), …
=> Add forton labels

assets/gaming/the_nothing_app.json, assets/infrastructure/one_click_sender.json
this is the same as the pull request #371
but I put the both OneClickSender and the nothing app in the same pull request because both are part of the same operation.
(screenshots and wallet for reward are also in that pull request)
=> Add OneClickSender and The Nothing App

assets/gaming/renttycoom.json, assets/gaming/renttycoon.json
HEX: 0:24102ce2ce057fc9ee06fa95e1713cd7b3f1c8d1826cb6b1a8955b4e68bb91d3
Bounceable: EQAkECzizgV_ye4G-pXhcTzXs_HI0YJstrGolVtOaLuR02aR
Non-bounceable: UQAkECzizgV_ye4G-pXhcTzXs_HI0YJstrGolVtOaLuR0ztU
My adress for rewards SBT : UQAIR5eIinIe4iFid26BX19pK_kJQYejzBOoQgCCnmVBp1EL
https://tonviewer.com/EQAkECzizgV_ye4G-pXhcTzXs_HI0YJstrGolVtOaLuR02aR
=> renttycoom

assets/lending/scroogers_bank.json
HEX: 0:fbe89fb4b5c7eda93fab97a93e482d7681981a1d304aa70beb51fc78228118ce
Bounceable: EQD76J-0tcftqT-rl6k-SC12gZgaHTBKpwvrUfx4IoEYzoy6
Non-bounceable: UQD76J-0tcftqT-rl6k-SC12gZgaHTBKpwvrUfx4IoEYztF_
It's a lending app, allowing to borrow ton/usdt against your NFTs
_EQD76J-0tcftqT-rl6k-SC12gZgaHTBKpwvrUfx4IoEYzoy6_  is used to give uncollaterized loans (and is owner of respective nft collections)
Other addresses are hardcoded on backend and sent as config 
They're used to issue ton/usdt loans against vouchers/other allowed NFTS
---
=> Add scroogers bank

assets/gaming/solariantech.json
HEX: 0:fd179c4125bce9e0241d5c8c41547af68ab93a2f4f8961c31e5e0a8fbb1f9c47
Bounceable: EQD9F5xBJbzp4CQdXIxBVHr2irk6L0-JYcMeXgqPux-cRz6O
Non-bounceable: UQD9F5xBJbzp4CQdXIxBVHr2irk6L0-JYcMeXgqPux-cR2NL
My wallet for rewards : UQA0JSdhSqKfr5J4u2aVOJHuosyBthVi7l1LaaiR95YHVj0-
https://tonviewer.com/transaction/04ec944214352d385609a47dd7f1b2042d414d67234568809823c11815cbeeca
=> solariantech

assets/gaming/riverland.json
HEX: 0:4db941ddffe02b7d951ef50d564339683c5387a3a2cf5b60b82920600233c70d
Bounceable: EQBNuUHd_-ArfZUe9Q1WQzloPFOHo6LPW2C4KSBgAjPHDXlY
Non-bounceable: UQBNuUHd_-ArfZUe9Q1WQzloPFOHo6LPW2C4KSBgAjPHDSSd
My wallet : UQDRr7UzFKz9GdmYq8WLeVmQ47cgg6GGNJ8lttm3_roOKX0c
https://getgems.io/collection/EQBNuUHd_-ArfZUe9Q1WQzloPFOHo6LPW2C4KSBgAjPHDXlY
https://t.me/RiverLandGameNews/706
=> riverland.json

assets/gaming/tonbattleground.json
HEX: 0:821a685838d7485a242ef095737d7ed252ad2b29cf7257adc3a8b32fa2615e28
Bounceable: EQCCGmhYONdIWiQu8JVzfX7SUq0rKc9yV63DqLMvomFeKGGX
Non-bounceable: UQCCGmhYONdIWiQu8JVzfX7SUq0rKc9yV63DqLMvomFeKDxS
My wallet for rewards SBT: UQD4l6u5A8Omcg5UtMdXPSq0s4Rp6vprls2naYvBdovf9Bf1
https://tonviewer.com/UQCCGmhYONdIWiQu8JVzfX7SUq0rKc9yV63DqLMvomFeKDxS
Mentions based on which it is possible to conclude the affiliation of this collection as well as this address for sending prizes to TON Battlegrounds.
https://tonviewer.com/UQCCGmhYONdIWiQu8JVzfX7SUq0rKc9yV63DqLMvomFeKDxS
https://t.me/ton_battleground/87408
https://t.me/ton_battleground/3361/136449
=> tonbattleground

assets/gaming/cryptid_hunter.json
HEX: 0:080bc92bfeacac6b95170172e186ea228f28c77ca92e856f6fcdef2d1d95e7ad
Bounceable: EQAIC8kr_qysa5UXAXLhhuoijyjHfKkuhW9vze8tHZXnrTDK
Non-bounceable: UQAIC8kr_qysa5UXAXLhhuoijyjHfKkuhW9vze8tHZXnrW0P
My wallet for rewards sbt: UQAl27oBR1GDG0NJdIirNlsyGP_1oanaHNij8kVH7ROyNPn8 
Proofs : 
https://t.me/cryptohunterm2p/23680
https://tonviewer.com/transaction/BuuE+kMZLUeRKrHXRCOu9DKHAEWGRGwlXAlYL94CU18=
=> cryptid_hunter

assets/gaming/workdogs.json
HEX: 0:27dd44a5729c6dfcc7dbdae4fe99562aed01d29c8438c9bafc2bcebba6b82067
Bounceable: EQAn3USlcpxt_Mfb2uT-mVYq7QHSnIQ4ybr8K867prggZ5D0
Non-bounceable: UQAn3USlcpxt_Mfb2uT-mVYq7QHSnIQ4ybr8K867prggZ80x
This wallet is distributing WD airdrop
Official announcement of 400m tokens airdrop
Transfer of 400m tokens from already marked project address
https://tonviewer.com/transaction/f86b4f7cd51ac10af1217037024fbdadfd46950db6174431e3d0b3c2028d4dc2 
And another transfer to cover gas costs
---
=> Add workdogs airdrop address

assets/cex/redotpay.json, assets/merchant/sticker_bot.json
Dune source:
https://dune.com/ton_foundation/ton-stars-withdrawals
thanks @rdmcd for help. He also proposed to add these Top Telegram Stars Payouts & Unlabelled addresses to our labelling contest.
=> Label Sticker Bot & More

assets/merchant/starsov.json
Bounceable: EQCDz6e7hfExr-VaDV0OJEWoAtL1q4TsNNSIRCLb2bc4KxHa
Non-bounceable: UQCDz6e7hfExr-VaDV0OJEWoAtL1q4TsNNSIRCLb2bc4K0wf
0:FE: 0:83cfa7bb85f131afe55a0d5d0e2445a802d2f5ab84ec34d4884422dbd9b7382b
This address is used by @StarsovBot (TG) to accept payments for buying Telegram Stars for users via Fragment
Proof:
My address for rewards: UQDbZ7VMQMe3zHsC5Wgg2dt1A9PtjryUWE7c8Lbs9f-LNS5D
=> add-starsov

assets/cex/okx.json
Added couple obvious wallets. Will add more soon.
Source: https://www.okx.com/proof-of-reserves/download
=> Add more OKX wallets

assets/gaming/giftbattles.json, assets/gaming/giftsbattle.json
HEX: 0:23ce9dd4836ec7d03f367958c5b5b1feb48a49ce2c891cb46d9f05bf7deb1e72
Bounceable: EQAjzp3Ug27H0D82eVjFtbH-tIpJziyJHLRtnwW_fesecljo
Non-bounceable: UQAjzp3Ug27H0D82eVjFtbH-tIpJziyJHLRtnwW_fesecgUt
=> giftsbattle

assets/cex/okx.json, assets/gaming/jetton.json
Source: proof of reserves https://www.okx.com/proof-of-reserves/download
=> Add more OKX addresses 

assets/gaming/time_ton.json
HEX: 0:6fcb580240e36196880318c2d17c258758ef97f93f0afa64537dc0d1cf431dc5
Bounceable: EQBvy1gCQONhlogDGMLRfCWHWO-X-T8K-mRTfcDRz0MdxXiC
Non-bounceable: UQBvy1gCQONhlogDGMLRfCWHWO-X-T8K-mRTfcDRz0MdxSVH
---
HEX: 0:e47086698fd491aaef66ac1d947e096d22f178e2164e03f2f43b6f65eaa64836
Bounceable: EQDkcIZpj9SRqu9mrB2UfgltIvF44hZOA_L0O29l6qZINuEL
Non-bounceable: UQDkcIZpj9SRqu9mrB2UfgltIvF44hZOA_L0O29l6qZINrzO
My wallet for rewards: UQBrxUSFqlZZprC3i41UCUAhggkbX1GrLxCl7lALZ0Rnkv0V
=> Add time_ton addresses

assets/gaming/tonbet.json
HEX: 0:d035c5bdf993375280d561a0017b52ab4adbdaf1a154f37024ff860171c4194f
Bounceable: EQDQNcW9-ZM3UoDVYaABe1KrStva8aFU83Ak_4YBccQZT0bO
Non-bounceable: UQDQNcW9-ZM3UoDVYaABe1KrStva8aFU83Ak_4YBccQZTxsL
My wallet for reward: UQBrxUSFqlZZprC3i41UCUAhggkbX1GrLxCl7lALZ0Rnkv0V
Proof: Address  hardcoded in Mini App...
=> Add tonbet

assets/gaming/tonpoker.json, assets/merchant/nowpayments.json
=> fix tonpoker: migrate addresses to nowpayments

assets/cex/pocketbroker.json
HEX: 0:59fe495690d4d25391d83e030c0ccf0f5cf936c296bca8849756d2764a477527
Bounceable: EQBZ_klWkNTSU5HYPgMMDM8PXPk2wpa8qISXVtJ2Skd1J18V
Non-bounceable: UQBZ_klWkNTSU5HYPgMMDM8PXPk2wpa8qISXVtJ2Skd1JwLQ
My wallet: UQBicUiXrZqxzPExSjw4UP4a4ltFscS-cX50SeLj4_eZ-4uN
https://tonviewer.com/EQAFFHMR6DdZ5CjWlEvNtxCRtA0nctmETx7m6FO6uA5cZI3U
=> pocket broker

assets/scammer/evpnpromo.json
HEX: 
0:3545d008f584fb4958c4f2339acb9a4ae3bd47ddc017dbf944ee50b04a1e4793
Bounceable: EQA1RdAI9YT7SVjE8jOay5pK471H3cAX2_lE7lCwSh5Hk6sJ
Non-bounceable: UQA1RdAI9YT7SVjE8jOay5pK471H3cAX2_lE7lCwSh5Hk_bM
This address spams transactions with an EVPN token that is supposed to represent ExpressVPN application:
The website shown in the transactions payload redirects to a website that most likely drains wallet that interact with it:
=> Add evpnpromo.json

assets/gaming/case.json, assets/gaming/primegifts.json, assets/gaming/rolls.json
added telegram gifts projects (roulettes and cases) and telegram gifts tag to use them in dune.com/rdmcd/telegram-gifts «gifts related projects»
=> add telegram-gifts tag to existing addresses and new address

assets/scammer/scammer.json
HEX:
0:3b2e5b597a8bd36ea46cf17b9b6a987c11ca3224cc621a74c4aef2d92d92816f
Bounceable: EQA7LltZeovTbqRs8Xubaph8EcoyJMxiGnTErvLZLZKBb7ka
Non-bounceable: UQA7LltZeovTbqRs8Xubaph8EcoyJMxiGnTErvLZLZKBb-Tf
HEX: 
0:ff82b4d4de7c366100f5df86ee7b50522edd993d360a7f4279e254db130dd533
Bounceable: EQD_grTU3nw2YQD134bue1BSLt2ZPTYKf0J54lTbEw3VM4CP
Non-bounceable: UQD_grTU3nw2YQD134bue1BSLt2ZPTYKf0J54lTbEw3VM91K
HEX:
0:9faefb67b72841ba407cd191a3e8092a3872b68790c9ff507855dbf64973a9b5
Bounceable: EQCfrvtntyhBukB80ZGj6AkqOHK2h5DJ_1B4Vdv2SXOptTC_
Non-bounceable: UQCfrvtntyhBukB80ZGj6AkqOHK2h5DJ_1B4Vdv2SXOptW16
=> Add multiple scammer addresses

assets/scripted-activity/sybil_EQBUJQ.json, assets/scripted-activity/sybil_EQDCwH.json
1) HEX: 0:542506157608ebd109140e11c253cc801772afed9bc10a759506de93d6e6101d
Bounceable: EQBUJQYVdgjr0QkUDhHCU8yAF3Kv7ZvBCnWVBt6T1uYQHSmn
Non-bounceable: UQBUJQYVdgjr0QkUDhHCU8yAF3Kv7ZvBCnWVBt6T1uYQHXRi
2) HEX: 0:c2c074d8adc2eae52bc9b0a40edecd25316409f570517913466c4e75e8d57fb1
Bounceable: EQDCwHTYrcLq5SvJsKQO3s0lMWQJ9XBReRNGbE516NV_sVo8
Non-bounceable: UQDCwHTYrcLq5SvJsKQO3s0lMWQJ9XBReRNGbE516NV_sQf5
1  
All addresses exhibit identical transaction patterns. A minimal amount of TON was withdrawn from the marked wallet in order to withdraw Mainnet CORE tokens from the bot. Afterward, the funds were returned to the original wallet.
2
All addresses that made deposits to the marked wallet exhibited only two transactions: a withdrawal from Puparty and a transfer to a single common wallet. This …
=> Add Sybil addresses

assets/gaming/1xbet.json, assets/gaming/888starz.json, assets/gaming/holdcoin.json, assets/gaming/mainet.json, assets/merchant/ecorpay.json
3 main additions:
1. new 1xbet addresses which received all deposited funds from previously labelled 1xbet addresses.
2. HOLD token distributor addresses. But unfortunately, I didn't find any social media post about this airdrop.
3. Add mainet address which receives TON payments (we already have CORE token payment receiver). They share the same "comment" style and were funded from related wallets.
=> Add labels 73

assets/scripted-activity/sybil_EQAsOw9.json
1) HEX: 0:2c3b0f6f43cb79c66b1d8304b225278aa9ecfe9deb226733928846413e081c0f
Bounceable: EQAsOw9vQ8t5xmsdgwSyJSeKqez-nesiZzOSiEZBPggcDziN
Non-bounceable: UQAsOw9vQ8t5xmsdgwSyJSeKqez-nesiZzOSiEZBPggcD2VI
I believe this address can be classified as a Sybil, although I don't fully understand the nature of such transactions. If we examine the address we want to flag, it shows identical transactions from the very beginning of its activity
If we look at the address to which the funds were sent (193.88 TON), we'll see a pattern with a couple of similar transactions to a single address.
This address also shows suspicious transactions, where funds were received from a single wallet and then transferred to a common third-party address — most likely related to claiming bonuses from Duckchain
We …
=> add sybil adress

assets/scripted-activity/sybil_tac_nft_EQAN_es.json
HEX: 0:0dfdeb0a8e2e6fe8221fef06102b8ae90b51bc29207a7a8121b8943cccf82eac
Bounceable: EQAN_esKji5v6CIf7wYQK4rpC1G8KSB6eoEhuJQ8zPgurBcd
Non-bounceable: UQAN_esKji5v6CIf7wYQK4rpC1G8KSB6eoEhuJQ8zPgurErY
1. I assume that this wallet has exhibited behavior typical of a Sybil participant and is likely associated with Peskar (the owner of tg split).
The connection to potential Sybil activity is based on several indirect indicators:
1 ) All transactions from this wallet are exclusively related to the purchase of NFTs from the First Force collection at a fixed price of 30 TON.
2 ) After each purchase, the remaining funds were transferred to the same address — EQAN_esKji5v6CIf7wYQK4rpC1G8KSB6eoEhuJQ8zPgurBcd — which has been included in labeling lists. From there, the funds were subsequently …
=> sybil_tac_nft

assets/cex/xrocket.json, assets/gaming/bombie.json, assets/gaming/mainet.json, assets/gaming/not_pixel.json, assets/gaming/vanilla_finance.json, assets/liquid_staking/ton_whales.json, assets/merchant/ecorpay.json, assets/wallet/pocketfi.json, assets/wallet/tonalytics.json
To count the full application activity in query https://dune.com/queries/4564764/7612752
> NOTE: If the token is used in multiple apps (e.g. $NOT), this may cause troubles.
=> Add jetton_masters for apps

assets/gaming/tonstation.json
HEX: 0:2c59cfbf15889f590f48f14c3314b978acd1d757b9139cd5171ea68d0438224f
Bounceable: EQAsWc-_FYifWQ9I8UwzFLl4rNHXV7kTnNUXHqaNBDgiT_6-
Non-bounceable: UQAsWc-_FYifWQ9I8UwzFLl4rNHXV7kTnNUXHqaNBDgiT6N7
=> tonstation

assets/merchant/mercuryo.json
HEX: 0:bb30f018b3d576e1de465fdd367ef68266c49e13ce28cf83c48ab482f23006ec
Bounceable: EQC7MPAYs9V24d5GX902fvaCZsSeE84oz4PEirSC8jAG7FIh
Non-bounceable: UQC7MPAYs9V24d5GX902fvaCZsSeE84oz4PEirSC8jAG7A_k
Next, USDT will be purchased and the payment will be processed via the Mercuryo payment gateway
https://tonviewer.com/transaction/0382b04263b2c53f617dcab26cda3d6ebba65b92c869e0ab425b11041be5af6f
It works within the concept specifically when entering Telegram and accessing the Telegram Wallet. That’s why, if you look at the transactions, all of them involve a transfer to the Telegram Wallet
My address for rewards: UQAbrZ8C6qUAgwfjZXLw54CabmmlL9Rnfem90yOPJ-fYBXbM
=> Add mercuryo label

assets/gaming/duckmyduck.json
HEX: 0:9cad001daa49593a07d92605aa4fe983055bdb0dc56e5bd16608e849af75aea3
Bounceable: EQCcrQAdqklZOgfZJgWqT-mDBVvbDcVuW9FmCOhJr3Wuo7XO
Non-bounceable: UQCcrQAdqklZOgfZJgWqT-mDBVvbDcVuW9FmCOhJr3Wuo-gL
My wallet: UQBicUiXrZqxzPExSjw4UP4a4ltFscS-cX50SeLj4_eZ-4uN
I believe that this address belongs to the owner of the duckmyduck app based on the following factors:
1) The presence of a Telegram user with the name "my duck" and "duckmyduck" — although it does not lead directly to the main channel, it provides an indirect clue
2) 
After earning profits from Fragment, large sums are transferred from the wallet to this address: UQA5QCbm10EAVJmmDGxQFbwdEvbGAYHEHPrHfA3THfYveKD7
If we analyze, for example, a withdrawal to Bybit with an already labeled address …
=> duckmyduck

assets/merchant/vseznayka_stars.json
HEX: 0:af316b985a98f89c6cbe73023a4cb12911c604c15a6195879caa2344f675f4a6
Bounceable:EQCvMWuYWpj4nGy-cwI6TLEpEcYEwVphlYecqiNE9nX0pvsk
Non-bounceable: UQCvMWuYWpj4nGy-cwI6TLEpEcYEwVphlYecqiNE9nX0pqbh
=> vseznayka_stars

assets/gaming/oreton.json
HEX: 0:dc12140a564f751e6c6cb9d0d0b23d27c6e5542dd83b6c0a21b5e843806aa668
Bounceable: EQDcEhQKVk91HmxsudDQsj0nxuVULdg7bAohtehDgGqmaOLX
Non-bounceable: UQDcEhQKVk91HmxsudDQsj0nxuVULdg7bAohtehDgGqmaL8S
My wallet : UQAjecHzmpKf8dkLDdI80RBZy39mEYoLn3LMx8RWe1lObcCu
https://tonviewer.com/transaction/6135925e0ad9b4e0a9a7a9e6ca3a94af1c1aab146c27cd991bb915ea0c27f826
=> add oreton label

assets/gaming/lucid_dreams.json
HEX: 0:0e2ff674cfa86660100c6f6fbfe9016f687aa00b3931907a48c4d67b3e581701
Bounceable: EQAOL_Z0z6hmYBAMb2-_6QFvaHqgCzkxkHpIxNZ7PlgXAS1F
Non-bounceable: UQAOL_Z0z6hmYBAMb2-_6QFvaHqgCzkxkHpIxNZ7PlgXAXCA
=> lucid_dreams

assets/merchant/sticker_bot.json
1.  HEX: 0:d23012960bb7ece4b6f7d4185533cc8494aad69c078f2cb2723a579cc4982299
Bounceable: EQDSMBKWC7fs5Lb31BhVM8yElKrWnAePLLJyOlecxJgimenO
Non-bounceable: UQDSMBKWC7fs5Lb31BhVM8yElKrWnAePLLJyOlecxJgimbQL
2. HEX: 0:e1bd729dd736d50e78d4353be11a52c11552e10812839dcb975dfc6331476587
Bounceable: EQDhvXKd1zbVDnjUNTvhGlLBFVLhCBKDncuXXfxjMUdlh4zB
Non-bounceable: UQDhvXKd1zbVDnjUNTvhGlLBFVLhCBKDncuXXfxjMUdlh9EE
1) ![image](https://github.com/user-attachments/assets/205a6ee8-1faa-4efb-9a69-cbdda1782f9b)
https://tonviewer.com/transaction/52ef414626066d4426ec68ff289a74567051e5ade498886227965c5b2d466489
2) https://telegra.ph/New-Rules-Same-Sticker-Magic-06-30-2
https://tonviewer.com/transaction/dd8a15ce47cb4168216416cb5d20d47e04f6010232cee48a352 …
=> sticker_bot

assets/wallet/hot_wallet.json
HEX: 0:0d11588cdc0290ce2e808f7b047b2a85bbca57aa1cbd43dc46a0877fd2aa7708
Bounceable: EQANEViM3AKQzi6Aj3sEeyqFu8pXqhy9Q9xGoId_0qp3CNVJ
Non-bounceable: UQANEViM3AKQzi6Aj3sEeyqFu8pXqhy9Q9xGoId_0qp3CIiM
My wallet: UQBicUiXrZqxzPExSjw4UP4a4ltFscS-cX50SeLj4_eZ-4uN
https://tonviewer.com/EQDzGzOGeksa5lcA89v1WJrwm-hTE_7tdITYk_f1ac8ZF1Mm
This contract is called when creating a Firedrop in the HotWallet app.
=> Hot Wallet

assets/gaming/wrapped_pi.json
1) HEX: 0:8bf1b8a2b576bd556b6a962d2341b90249f4ac9982fd5a8cbda361fee3b067ac
Bounceable: EQCL8biitXa9VWtqli0jQbkCSfSsmYL9Woy9o2H-47BnrFnN
Non-bounceable: UQCL8biitXa9VWtqli0jQbkCSfSsmYL9Woy9o2H-47BnrAQI
2) HEX: 0:c0541cb60d95e2464de897f577101c604f0d04f0769635305712885eef310e5f
Bounceable: EQDAVBy2DZXiRk3ol_V3EBxgTw0E8HaWNTBXEohe7zEOX6H8
Non-bounceable: UQDAVBy2DZXiRk3ol_V3EBxgTw0E8HaWNTBXEohe7zEOX_w5
=> Wrapped Pi

assets/merchant/gifts_giveaway.json
HEX: 0:c30e4121097a34ada86f53f6b314cd3ea141a94a338b02396e2ec577f21022d0
Bounceable: EQDDDkEhCXo0rahvU_azFM0-oUGpSjOLAjluLsV38hAi0GGc
Non-bounceable: UQDDDkEhCXo0rahvU_azFM0-oUGpSjOLAjluLsV38hAi0DxZ
I believe that this address is related to gifts giveaway and is used for withdrawing Telegram Stars, based on the following facts:
1) The Telegram domain giftaway was purchased, and there was an approximate transfer to the TON address (clicker.t.me) without any payment.
2)  [clicker.t.me](https://tonviewer.com/EQAjpjLqOHR0RTJTFRM6S6aPJYsDDHC4SU8MAnAVTpW_sakq?section=nfts)
It has several active channels and a bot, but notably, this address does not receive Telegram Stars withdrawals from Fragment, while the one we're trying to label …
=> Gifts Giveaway

assets/merchant/sticker_bot.json
HEX: 0:3e6a0d7197987e9338dc93b8386d2bd075ace1832003948544ef705554f589b9
Bounceable: EQA-ag1xl5h-kzjck7g4bSvQdazhgyADlIVE73BVVPWJuUPF
Non-bounceable: UQA-ag1xl5h-kzjck7g4bSvQdazhgyADlIVE73BVVPWJuR4A
I believe that this address was used for a refund from a raffle in the Sticker Store based on the following facts: 
1) the funds for the refunds were received from the address [UQCaljNYaoBXdIo8dQC42gmTlgR07kmTER40Ip86A44GTCte](https://tonviewer.com/UQCaljNYaoBXdIo8dQC42gmTlgR07kmTER40Ip86A44GTCte)
https://intel.arkm.com/explorer/address/0:3E6A0D7197987E9338DC93B8386D2BD075ACE1832003948544EF705554F589B9
In turn, this address received funds from thedns-tg-channel.ton (which had previously been labeled as an address belonging to the …
=> Sticker Store

assets/gaming/tonstation.json
HEX: 0:62a9764a0eaeb08ac15e0e0c8c5b2613be33ff08b659e6a7be7ed9f6532d0856
Bounceable: EQBiqXZKDq6wisFeDgyMWyYTvjP_CLZZ5qe-ftn2Uy0IVt67
Non-bounceable: UQBiqXZKDq6wisFeDgyMWyYTvjP_CLZZ5qe-ftn2Uy0IVoN-
My wallet : UQBqDUtXzQ42H41hDPj9nN9vs7q4zFzhX-rArtIVZ8DOoFai
I believe that this address belongs to Ton Station based on the following arguments:
1) All wallet activity is exclusively focused on the SOON token.
2) Among the first transactions on this address were incoming transfers of SOON tokens, which are subsequently actively distributed from this wallet (address: [UQDEYvty2KvuaThAVeWerzXTyfDOSPrH36La93ww1w_sU9BU](https://tonviewer.com/UQDEYvty2KvuaThAVeWerzXTyfDOSPrH36La93ww1w_sU9BU)).
- Transaction analysis shows that significant amounts associated with Ton Station have been sent from this …
=> Add TonStation address

assets/scripted-activity/sybil_ EQA8uvz.json
HEX: 0:3cbafce9a1e7727218841efc1025a11795fde46114904a0db5e896db49272d77
Bounceable: EQA8uvzpoedychiEHvwQJaEXlf3kYRSQSg216JbbSSctdxoC
Non-bounceable: UQA8uvzpoedychiEHvwQJaEXlf3kYRSQSg216JbbSSctd0fH
I am confident that this address belongs to Sybil, based on the following evidence:
The addresses interacting with the one we are attempting to label demonstrate identical behavior, including interactions with pay.muton, Sidefans, and the receipt of DOGS tokens(this pattern of activity has been consistently present since the wallet’s very first transactions).
* The screenshots provided show the typical behavior of wallets that interact with the address we are attempting to label.
=> add sybil address

assets/infrastructure/ethena.json
HEX:
0:b2585f51d76184e4173e6abfb0dd3b9308478f3f75405aafe6f10aa0b50b90d8
Mainnet:
Bounceable:
EQCyWF9R12GE5Bc-ar-w3TuTCEePP3VAWq_m8QqgtQuQ2EfE
UQCyWF9R12GE5Bc-ar-w3TuTCEePP3VAWq_m8QqgtQuQ2BoB
=> USDE reward sender

assets/gaming/prosper_pig.json, assets/gaming/tokencarnival_pro.json
HEX: 0:d35c6a17f24868b44492475fc9cbaa550eb86dc975c7356554970cd70936e082
Bounceable: EQDTXGoX8khotESSR1_Jy6pVDrhtyXXHNWVUlwzXCTbgggv9
Non-bounceable: UQDTXGoX8khotESSR1_Jy6pVDrhtyXXHNWVUlwzXCTbgglY4
My wallet for rewards : UQB_gViZmfgPJet5ddED39SF9YJK8bYiL9K-XTapnqUsmGr4
=> Add Token Carnival pro

assets/gaming/epic_gift.json
HEX: 0:f61b85c81ea5d83d622c6a03e7970c126098b5a1bd06357a6bbf2ad6a3ecc550
Bounceable: EQD2G4XIHqXYPWIsagPnlwwSYJi1ob0GNXprvyrWo-zFUMep
Non-bounceable: UQD2G4XIHqXYPWIsagPnlwwSYJi1ob0GNXprvyrWo-zFUJps
My wallet for rewards: UQBqDUtXzQ42H41hDPj9nN9vs7q4zFzhX-rArtIVZ8DOoFai
=> Add new labels — Epic Gift
